### ISSUE TITLE
Error building Python-3.8.2-GCCcore-9.3.0.eb

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyconfigs#10622]
Oh how I wished to have a really verbose easybuild :-)

```== processing EasyBuild easyconfig /software/Stages/2019b/easybuild-easyconfigs-develop-branch/easybuild/easyconfigs/p/Python/Python-3.8.2-GCCcore-9.3.0.eb
== building and installing Python/3.8.2-GCCcore-9.3.0...
== fetching files...
ERROR: Traceback (most recent call last):
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/main.py", line 114, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3183, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3087, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 2926, in run_step
    step_method(self)()
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/easyblocks/generic/configuremake.py", line 180, in fetch_step
    super(ConfigureMake, self).fetch_step(*args, **kwargs)
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 1795, in fetch_step
    self.exts = self.fetch_extension_sources(skip_checksums=skip_checksums)
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 520, in fetch_extension_sources
    src_fn = self.obtain_file(fn, extension=True, urls=source_urls, force_download=force_download)
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 727, in obtain_file
    alt_url = derive_alt_pypi_url(fullurl)
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/tools/filetools.py", line 519, in derive_alt_pypi_url
    cand_urls = pypi_source_urls(pkg_name)
  File "/software/Stages/2019b/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/tools/filetools.py", line 498, in pypi_source_urls
    parsed_html = ElementTree.parse(urls_html)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 143, column 306
 (at easybuild/main.py:147 in build_and_install_software)
```

**Comment by boegel** [comment]
@surak This is a known issue that is already fixed in `develop`, see https://github.com/easybuilders/easybuild/issues/621#issuecomment-625429463 for more information
