### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte [...] upon Intel toolchain 2019.5.281 install

### ISSUE THREAD

**Issue by Falkor** [easybuilders/easybuild-easyconfigs#10742]
When trying to build Intel toolchains on RHEL 8.1 (and Environment Modules TCL), I got the $subject error. 

```bash 
$> cat /etc/redhat-release
Red Hat Enterprise Linux release 8.1 (Ootpa)
$> env | grep -i utf
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
$> eb --version
This is EasyBuild 4.2.1 (framework: 4.2.1, easyblocks: 4.2.1) on host spartan126
$> eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath             (F) = /dev/shm
configfiles           (E) = </path/to>/sw/config/easybuild.cfg
containerpath         (E) = </path/to>/sw/apps/spartan/epyc/local/containers
git-working-dirs-path (E) = /home_nfs_robin_ib/xvarrettes/git/github.com/ULHPC
github-user           (F) = ULHPC
ignore-index          (F) = True
installpath           (E) = </path/to>/sw/apps/spartan/epyc/local
job-backend           (F) = Slurm
module-naming-scheme  (E) = CategorizedModuleNamingScheme
module-syntax         (E) = Tcl
modules-tool          (E) = EnvironmentModules
packagepath           (E) = </path/to>/sw/apps/spartan/epyc/local/packages
prefix                (E) = </path/to>/sw/apps/spartan/epyc/local
repositorypath        (E) = </path/to>/sw/apps/spartan/epyc/local/ebfiles_repo
robot-paths           (E) = </path/to>/sw/easyconfigs, </path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/easybuild/easyconfigs, <home>/git/github.com/ULHPC/easybuild-easyconfigs/easybuild/easyconfigs,
sourcepath            (E) = </path/to>/sw/apps/sources:</path/to>/sw/apps/spartan/epyc/local/sources:</path/to>/sw/sources:/opt/apps/sources
tmp-logdir            (E) = </path/to>/sw/logs/easybuild
```

The build fail as follows: 
```bash 
$> eb iccifort-2019.5.281.eb  -r --rebuild --debug
== temporary log file in case of crash </path/to>/sw/logs/easybuild/easybuild-0qk57id4.log
== resolving dependencies ...
== processing EasyBuild easyconfig </path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/easybuild/easyconfigs/i/iccifort/iccifort-2019.5.281.eb
== building and installing compiler/iccifort/2019.5.281...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
ERROR: Traceback (most recent call last):
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/main.py", line 115, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3234, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3139, in run_all_steps
    self.run_step(step_name, step_methods)
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 2994, in run_step
    step_method(self)()
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/easyblocks/generic/intelbase.py", line 296, in configure_step
    self.parse_components_list()
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/easyblocks/generic/intelbase.py", line 175, in parse_components_list
    mediaconfig = read_file(mediaconfigpath)
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/tools/filetools.py", line 195, in read_file
    txt = handle.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 306: ordinal not in range(128)
```

* `export PYTHONIOENCODING=utf8` did not help 
* Setting `LANG` `LC_ALL` to en_US.UTF-8 as suggested in [Easybuild Issue #2037](https://github.com/easybuilders/easybuild-easyconfigs/issues/2037#issuecomment-146158392) did not help neither... 
* the Intel licence file seems to have the correct encoding:

```
file -i $INTEL_LICENSE_FILE
<path/to/intel_licence>.lic: text/plain; charset=us-ascii
```

Detailed logs: 

```
== 2020-06-02 18:54:39,679 templates.py:163 DEBUG config: <easybuild.framework.easyconfig.easyconfig.EasyConfig object at 0x7f9a743c75f8>
== 2020-06-02 18:54:39,679 templates.py:190 DEBUG version found in easyconfig is 2019.5.281
== 2020-06-02 18:54:39,679 templates.py:257 DEBUG name: bitbucket_account, config: %(namelower)s
== 2020-06-02 18:54:39,679 templates.py:257 DEBUG name: github_account, config: %(namelower)s
== 2020-06-02 18:54:39,680 templates.py:257 DEBUG name: name, config: iccifort
== 2020-06-02 18:54:39,680 templates.py:257 DEBUG name: parallel, config: 256
== 2020-06-02 18:54:39,680 templates.py:257 DEBUG name: version, config: 2019.5.281
== 2020-06-02 18:54:39,680 templates.py:257 DEBUG name: versionsuffix, config:
== 2020-06-02 18:54:39,680 templates.py:257 DEBUG name: versionprefix, config:
== 2020-06-02 18:54:39,680 easyblock.py:2974 INFO Running method configure_step part of step configure
== 2020-06-02 18:54:39,680 intelbase.py:197 DEBUG Cleaning up /tmp/xvarrettes/easybuild_intel...
== 2020-06-02 18:54:39,681 config.py:569 DEBUG software install path as specified by 'installpath' and 'subdir_software': </path/to>/sw/apps/spartan/epyc/local/software
== 2020-06-02 18:54:39,681 filetools.py:1605 INFO Removing lock </path/to>/sw/apps/spartan/epyc/local/software/.locks/_home_path_to_sw_apps_spartan_epyc_local_software_iccifort_2019.5.281.lock...
== 2020-06-02 18:54:39,682 filetools.py:330 INFO Path </path/to>/sw/apps/spartan/epyc/local/software/.locks/_home_path_to_sw_apps_spartan_epyc_local_software_iccifort_2019.5.281.lock successfully removed.
== 2020-06-02 18:54:39,683 filetools.py:1609 INFO Lock removed: </path/to>/sw/apps/spartan/epyc/local/software/.locks/_home_path_to_sw_apps_spartan_epyc_local_software_iccifort_2019.5.281.lock
== 2020-06-02 18:54:39,687 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Traceback (most recent call last):
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/main.py", line 115, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3234, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3139, in run_all_steps
    self.run_step(step_name, step_methods)
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 2994, in run_step
    step_method(self)()
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/easyblocks/generic/intelbase.py", line 296, in configure_step
    self.parse_components_list()
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/easyblocks/generic/intelbase.py", line 175, in parse_components_list
    mediaconfig = read_file(mediaconfigpath)
  File "</path/to>/sw/apps/spartan/epyc/local/software/EasyBuild/4.2.1/lib/python3.6/site-packages/easybuild/tools/filetools.py", line 195, in read_file
    txt = handle.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 306: ordinal not in range(128)
 (at easybuild/main.py:148 in build_and_install_software)
```

Any help would be welcome ;)

**Comment by Micket** [comment]
This is not the license file, it's the `pset/mediaconfig.xml` file inside the sources. This is indeed a utf-8 encoded file, as it contains many translations.

I can't see that easybuild does anything wrong here, it's a standard `file.read` operation. We don't specify any particular encoding, so, it should be picking up on locale.
(also, intel is lazy and haven't specified: `<?xml version = "1.0" encoding = "UTF-8" standalone = "no" ?>` in their xml file, like they really really really should be doing)
Perhaps we should start specifying the encoding manually since we know the true encoding of this file.

What does `locale` say on your machine?

**Comment by Falkor** [comment]
```
$> locale
LANG=en_US.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

**Comment by akesandgren** [comment]
so have you tried with
env LC_CTYPE=en_US.UTF8 eb ...

**Comment by Falkor** [comment]
No change, same issue ;(

**Comment by Falkor** [comment]
OK, for some reason, if you `export LC_ALL=en_US.UTF-8` within the full bash session it seems to pass the build but now fail on the sanity check. As it is likely a separate issue, I'll close this ticket. 
For archiving purpose, here are an extract of my exchanges on Slack for this last issue with the suggestion to go for 2020a...: 

> __Falkor__: Hi easybuilders. I see that intel-2019b toolchains depends on 2018 iMPI (impi-2018.5.288-iccifort-2019.5.281.eb). Is there a reason for that? I struggle with the build on AMD Epyc / RHEL 8.1- I have to set `I_MPI_PMI_LIBRARY` (to  `/usr/lib64/libpmi.so`) to have the build OK but sanity checks are stalled... thus I was considering trying a newer version
> __ake_s__: Yes, there where serious problems with impi 2019 in the beginning. even intel acknowledge that... Checkout the hooks in the contrib section of the framework git repo, that's how we deal with PMI for IMPI up until that version
> __boegel__: I'd advise using the 2020a toolchains on AMD Epyc
