### ISSUE TITLE
ParaView/5.8.0-foss-2020a-Python-3.8.2-mpi crashes on prepare.

### ISSUE THREAD

**Issue by terjekv** [easybuilders/easybuild-easyconfigs#11203]
Trying to install ParaView/5.8.0-foss-2020a-Python-3.8.2-mpi on aarch64 causes a crash in EasyBuild. It would appear to be related to parsing of the compiler options?

```
== temporary log file in case of crash /tmp/eb-xyx8mvio/easybuild-mlneyoxv.log

WARNING: Deprecated functionality, will no longer work in v5.0: Support for Lmod version < 7.0.0 is deprecated, found version 6.6; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== resolving dependencies ...
== processing EasyBuild easyconfig /tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-easyconfigs/easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-foss-2020a-Python-3.8.2-mpi.eb
== building and installing ParaView/5.8.0-foss-2020a-Python-3.8.2-mpi...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
ERROR: Traceback (most recent call last):
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/main.py", line 115, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/framework/easyblock.py", line 3301, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/framework/easyblock.py", line 3204, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/framework/easyblock.py", line 3059, in run_step
    step_method(self)()
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/framework/easyblock.py", line 2081, in prepare_step
    rpath_include_dirs=self.rpath_include_dirs)
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/toolchains/mpi/openmpi.py", line 76, in prepare
    super(OpenMPI, self).prepare(*args, **kwargs)
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/tools/toolchain/toolchain.py", line 850, in prepare
    self.set_variables()
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/tools/toolchain/compiler.py", line 162, in set_variables
    self._set_compiler_flags()
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/tools/toolchain/compiler.py", line 277, in _set_compiler_flags
    self.variables.nextend('PRECFLAGS', precflags[:1])
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/tools/variables.py", line 548, in _passthrough
    res = actual_function(*args, **kwargs)
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/tools/variables.py", line 316, in nextend
    if not self._str_ok(el):
  File "/tmp/terjekv/EasyBuild-develop-9aBrAF/easybuild-framework/easybuild/tools/variables.py", line 350, in _str_ok
    test = x is not None and len(x) > 0
TypeError: object of type 'bool' has no len()
```

The value of `x` running through this method is:

```
gcc
gcc
gcc
gcc
g++
g++
g++
g++
gfortran
gfortran
gfortran
gfortran
gfortran
gfortran
gfortran
gfortran
gfortran
gfortran
gfortran
gfortran
-lpthread
-lm
-lgfortran

O2
mcpu=native
False
```

**Comment by terjekv** [comment]
A gcc framework patch for aarch64 caused this. Rolled back now. Looks okay.
