### ISSUE TITLE
Tkinter-2.7.16-GCCcore-8.3.0.eb fails to work against python built with UCS

### ISSUE THREAD

**Issue by terjekv** [easybuilders/easybuild-easyconfigs#11931]
Python-2.7.16 is seemingly built with UCS support. This causes issues for Tkinter, ala: https://github.com/pytorch/pytorch/issues/591

I may have to attempt to migrate this to python3, but the code in question expects 2.7 and imports `Tkinter`, while on python3, it's `tkinter` (lowercase "t").

```
== 2020-12-23 21:44:23,247 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Sanity check failed: sanity check command python -c 'import Tkinter' exited with code 1 (output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/uio/modules/rhel8/easybuild/software/Python/2.7.16-GCCcore-8.3.0/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: /opt/uio/modules/rhel8/easybuild/software/Tkinter/2.7.16-GCCcore-8.3.0/lib/python2.7/_tkinter.so: undefined symbol: PyUnicodeUCS4_AsUTF8String
) (at easybuild/framework/easyblock.py:2799 in _sanity_check_step)

```

**Comment by branfosj** [comment]
As this bug is in a now archived easyconfig I'll close the issue. If this is a problem with a newer version then please do let us know.
