### ISSUE TITLE
Recent ReFrame easyconfigs rely on system Python having pip

### ISSUE THREAD

**Issue by ocaisa** [easybuilders/easybuild-easyconfigs#12326]
The `2020.12` stack from EESSI had no pip in the system Python. This caused recent ReFrame easyconfigs to fail to install because the `pip` in the extension list is not installed in a usable way. The problem manifests itself as:
```
== 2021-03-03 08:05:57,532 pythonpackage.py:210 INFO Determining pip version...
== 2021-03-03 08:05:57,532 run.py:222 INFO running cmd: pip --version 
== 2021-03-03 08:05:57,855 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/software/EasyBuild/4.3.3/lib/python3.8/site-packages/easybuild/base/exceptions.py:124 in __init__): cmd "pip --version" exited with exit code 1 and output:
Traceback (most recent call last):
  File "/home/ocais1/.local/easybuild/software/ReFrame/3.4.1/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==21.0.1', 'console_scripts', 'pip')())
  File "/home/ocais1/.local/easybuild/software/ReFrame/3.4.1/bin/pip", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/cvmfs/pilot.eessi-hpc.org/2020.12/compat/linux/x86_64/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/cvmfs/pilot.eessi-hpc.org/2020.12/compat/linux/x86_64/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pip
 (at easybuild/software/EasyBuild/4.3.3/lib/python3.8/site-packages/easybuild/tools/run.py:533 in parse_cmd_output)
```

They are also missing required dependencies as per https://github.com/eth-cscs/reframe/pull/1767/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R28

**Comment by boegel** [comment]
This can be closed now, easyconfig for ReFrame 3.6.2 which was merged in #13096 includes a fix for this
