### ISSUE TITLE
building graphviz/0.8.2-intel-2018a-Python-3.6.4.eb fails with XML and PyPI error messages

### ISSUE THREAD

**Issue by moravveji** [easybuilders/easybuild-easyconfigs#12416]
Hi.

I tried to build the `graphviz/0.8.2-intel-2018a-Python-3.6.4` module on our Haswell nodes (ThinKing, Tier2), and it went OK. However, repeating the same build (the same EB version 4.2.0, the same toolchain intel/2018a) fails on Breniac with the following error:

```bash
== fetching files...
ERROR: Traceback (most recent call last):
  File "/vsc-hard-mounts/leuven-data/sys/x0090231/easybuild-boostrap/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/main.py", line 114, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/data/leuven/sys/x0090231/easybuild-boostrap/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3183, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/data/leuven/sys/x0090231/easybuild-boostrap/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 3087, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/data/leuven/sys/x0090231/easybuild-boostrap/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 2926, in run_step
    step_method(self)()
  File "/data/leuven/sys/x0090231/easybuild-boostrap/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 1748, in fetch_step
    self.fetch_sources(self.cfg['sources'], checksums=self.cfg['checksums'])
  File "/data/leuven/sys/x0090231/easybuild-boostrap/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 380, in fetch_sources
    urls=source_urls, git_config=git_config)
  File "/data/leuven/sys/x0090231/easybuild-boostrap/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/framework/easyblock.py", line 727, in obtain_file
    alt_url = derive_alt_pypi_url(fullurl)
  File "/data/leuven/sys/x0090231/easybuild-boostrap/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/tools/filetools.py", line 519, in derive_alt_pypi_url
    cand_urls = pypi_source_urls(pkg_name)
  File "/data/leuven/sys/x0090231/easybuild-boostrap/software/EasyBuild/4.2.0/lib/python2.7/site-packages/easybuild/tools/filetools.py", line 498, in pypi_source_urls
    parsed_html = ElementTree.parse(urls_html)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 6, column 4
```

I see traces of `pypi` and `xml` therein, but not sure which one is actually in charge.

Few questions:
- Why I do not get this error on Haswell nodes? 
- What could be different between the two machines? PyPI versions? XML library versions? sth else?
- Any suggestions how to fix this?

I have attached the build logfile in `debug` mode.

Thanks
Ehsan
[graphviz.log.tar.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/6150055/graphviz.log.tar.gz)

**Comment by boegel** [comment]
@moravveji You're hitting a bug that was fixed in EasyBuild v4.2.1, see https://github.com/easybuilders/easybuild-framework/pull/3303 + https://github.com/easybuilders/easybuild-framework/pull/3329 (and https://docs.easybuild.io/en/latest/Release_notes.html#easybuild-v4-2-1-may-20th-2020).

I propose you update to the latest EasyBuild, which should be safe to do. The easiest way is with `eb --install-latest-eb-release` (which will install the latest EasyBuild release as a module, it won't touch your existing EasyBuild installation).
