### ISSUE TITLE
h5py-3.1.0-foss-2020b fails 

### ISSUE THREAD

**Issue by LHurst-JM** [easybuilders/easybuild-easyconfigs#13424]
When building h5py-3.1.0-foss-2020b.eb in a cluster without internet access having pre-fetched sources with `eb -Tr --fetch h5py-3.1.0-foss-2020b.eb` it fails at install step due to trying to download numpy 1.17.5 during install phase.  (SciPy-bundle, on which it depends, includes numpy 1.19.4).

eb -Tr h5py-3.1.0-foss-2020b.eb output:

```
== processing EasyBuild easyconfig /mnt/apps/easybuild/2020b/easybuild-easyconfigs/easybuild/easyconfigs/h/h5py/h5py-3.1.0-foss-2020b.eb
== building and installing h5py/3.1.0-foss-2020b...
  >> installation prefix: /mnt/apps/easybuild/2020b/EL-7-sky/software/h5py/3.1.0-foss-2020b
== fetching files...
  >> sources:
  >> /mnt/apps/easybuild/2020b/src/h/h5py/h5py-3.1.0.tar.gz [SHA256: 1e2516f190652beedcb8c7acfa1c6fa92d99b42331cbef5e5c7ec2d65b0fc3c2]
== creating build dir, resetting environment...
  >> build dir: /dev/shm/eb-build/h5py/3.1.0/foss-2020b
== unpacking...
  >> running command:
        [started at: 2021-07-13 11:16:53]
        [working dir: /dev/shm/eb-build/h5py/3.1.0/foss-2020b]
        [output logged in /tmp/eb-nevhz_6c/easybuild-run_cmd-ix16jvcf.log]
        tar xzf /mnt/apps/easybuild/2020b/src/h/h5py/h5py-3.1.0.tar.gz
  >> command completed: exit 0, ran in < 1s
== patching...
== preparing...
  >> loading toolchain module: foss/2020b
  >> loading modules for build dependencies:
  >>  * pkgconfig/1.5.1-GCCcore-10.2.0-python
  >> loading modules for (runtime) dependencies:
  >>  * Python/3.8.6-GCCcore-10.2.0
  >>  * SciPy-bundle/2020.11-foss-2020b
  >>  * HDF5/1.10.7-gompi-2020b
  >> defining build environment for foss/2020b toolchain
== configuring...
== building...
== testing...
== installing...
  >> running command:
        [started at: 2021-07-13 11:17:01]
        [working dir: /dev/shm/eb-build/h5py/3.1.0/foss-2020b/h5py-3.1.0]
        [output logged in /tmp/eb-nevhz_6c/easybuild-run_cmd-vpg_9t45.log]
        HDF5_MPI=ON HDF5_DIR="$EBROOTHDF5"  pip install --prefix=/mnt/apps/easybuild/2020b/EL-7-sky/software/h5py/3.1.0-foss-2020b  --no-deps  --ignore-installed  --no-index  --no-build-isolation  .
  >> command completed: exit 1, ran in 00h00m14s
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/eb-build/h5py/3.1.0/foss-2020b): build failed (first 300 chars): cmd "HDF5_MPI=ON HDF5_DIR="$EBROOTHDF5"  pip install --prefix=/mnt/apps/easybuild/2020b/EL-7-sky/software/h5py/3.1.0-foss-2020b  --no-deps  --ignore-installed  --no-index  --no-build-isolation  ." exited with exit code 1 and output:
Processing /dev/shm/eb-build/h5py/3.1.0/foss-2020b/h5py-3.1.0
    P (took 23 sec)
== Results of the build can be found in the log file(s) /tmp/eb-nevhz_6c/easybuild-h5py-3.1.0-20210713.111653.lrQsJ.log
ERROR: Build of /mnt/apps/easybuild/2020b/easybuild-easyconfigs/easybuild/easyconfigs/h/h5py/h5py-3.1.0-foss-2020b.eb failed (err: 'build failed (first 300 chars): cmd "HDF5_MPI=ON HDF5_DIR="$EBROOTHDF5"  pip install --prefix=/mnt/apps/easybuild/2020b/EL-7-sky/software/h5py/3.1.0-foss-2020b  --no-deps  --ignore-installed  --no-index  --no-build-isolation  ." exited with exit code 1 and output:\nProcessing /dev/shm/eb-build/h5py/3.1.0/foss-2020b/h5py-3.1.0\n    P')
```

Install stage log (/tmp/eb-nevhz_6c/easybuild-run_cmd-vpg_9t45.log):

```
# output for command: HDF5_MPI=ON HDF5_DIR="$EBROOTHDF5"  pip install --prefix=/mnt/apps/easybuild/2020b/EL-7-sky/software/h5py/3.1.0-foss-2020b  --no-deps  --ignore-installed  --no-index  --no-build-isolation  .

Processing /dev/shm/eb-build/h5py/3.1.0/foss-2020b/h5py-3.1.0
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/bin/python /mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/eb-nevhz_6c/tmphdbn_3on
         cwd: /tmp/eb-nevhz_6c/pip-req-build-o13aciih
    Complete output (46 lines):
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)'))': /simple/numpy/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)'))': /simple/numpy/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)'))': /simple/numpy/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)'))': /simple/numpy/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1124)'))': /simple/numpy/
    ERROR: Could not find a version that satisfies the requirement numpy==1.17.5 (from versions: none)
    ERROR: No matching distribution found for numpy==1.17.5
    Traceback (most recent call last):
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/eb-nevhz_6c/tmpvlmyyo82', '--quiet', 'numpy==1.17.5']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 158, in <module>
        setup(
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/__init__.py", line 164, in setup
        _install_setup_requires(attrs)
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/__init__.py", line 159, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/dist.py", line 699, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
        dist = best[req.key] = env.best_match(
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/eb-nevhz_6c/tmpvlmyyo82', '--quiet', 'numpy==1.17.5']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/bin/python /mnt/apps/easybuild/2020b/EL-7-sky/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/eb-nevhz_6c/tmphdbn_3on Check the logs for full command output.
```

**Comment by LHurst-JM** [comment]
The [h5py setup.py](https://github.com/h5py/h5py/blob/3.1.0/setup.py) selects the minimum version of numpy it depends on based on the python interpretor version:

```python
# Minimum supported versions of Numpy & Cython depend on the Python version
NUMPY_MIN_VERSIONS = [
    # Numpy    Python
    ('1.14.5', "=='3.7'"),
    ('1.17.5', "=='3.8'"),
    ('1.19.3', ">='3.9'"),
]
```

2020b general uses 3.8.6(-GCCcore-10.2.0), so it selects 1.17.5.  It then uses this as a minimum version for runtime (`>=` selector) but specifically this version for setup (`==` selector), hence the problem:

```
# these are required to use h5py
RUN_REQUIRES = ["cached-property; python_version<'3.8'"] + [
    f"numpy >={np_min}; python_version{py_condition}"
    for np_min, py_condition in NUMPY_MIN_VERSIONS
]

# these are required to build h5py
# For packages we link to (numpy, mpi4py), we build against the oldest
# supported version; h5py wheels should then work with newer versions of these.
# Downstream packagers - e.g. Linux distros - can safely build with newer
# versions.
SETUP_REQUIRES = [
    'pkgconfig',
    f"Cython >=0.29; python_version<'3.8'",
    f"Cython >=0.29.14; python_version>='3.8'",
] + [
    f"numpy =={np_min}; python_version{py_condition}"
    for np_min, py_condition in NUMPY_MIN_VERSIONS
]
```

I am pretty sure EasyBuild falls into the "Downstream packagers" camp, do I will patch this to use `>=` during setup as well (my though here being that this future-proofs the patch, rather than patch to set the minimum version to the default in the 2020b toolchain, at the risk of accidently accepting a non-default higher version).

**Comment by branfosj** [comment]
Looking a it further there is

```python
# Set the environment variable H5PY_SETUP_REQUIRES=0 if we need to skip
# setup_requires for any reason.
if os.environ.get('H5PY_SETUP_REQUIRES', '1') == '0':
    SETUP_REQUIRES = []
```

So long as the install requirements are met (the `>=` requirements) it _should_ be safe to set that environment variable at build time to avoid the issue.

**Comment by LHurst-JM** [comment]
Thank Simon ("hi" by the way!), adding that to the eb is going to be easier than patching the source - when I read the comment I thought they would have provided a workaround for "Downstream packagers" and managed to overlook it 😉 

Adding H5PY_SETUP_REQUIRES=0 to the existing preinstallopts  works.

My preinstallopts now reads:

```
preinstallopts = 'HDF5_MPI=ON HDF5_DIR="$EBROOTHDF5" H5PY_SETUP_REQUIRES=0 '
```

I'll create a PR.
