### ISSUE TITLE
test_profiler.py hanging in PyTorch 1.8.1 and 1.9.0 installation with fosscuda

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#13791]
This seems to be due to a bug in the CUDA drivers 465.19.01, which we currently have installed on our GPU cluster, see https://github.com/pytorch/pytorch/issues/60158 .

I tried out a naive-ish patch based on the information in that issue (in particular https://github.com/pytorch/pytorch/issues/60158#issuecomment-867263191), but that didn't fix the problem for me:

```diff
--- pytorch/test/test_profiler.py.orig	2021-04-28 19:35:29.000000000 +0200
+++ pytorch/test/test_profiler.py	2021-08-22 14:48:30.452624877 +0200
@@ -24,6 +24,12 @@
 import pickle


+# workaround for hang with CUDA driver 465.19.01
+# see https://github.com/pytorch/pytorch/issues/60158
+with torch.profiler.profile() as profiler:
+    pass
+
+
 @unittest.skipIf(not HAS_PSUTIL, "Requires psutil to run")
 @unittest.skipIf(TEST_WITH_ASAN, "Cannot test with ASAN")
 @unittest.skipIf(IS_WINDOWS, "Test is flaky on Windows")
```

Any suggestions @Flamefire? Should we just skip `test_profiler`?

**Comment by Micket** [comment]
I'm running driver 470.57.02 and with PyTorch 1.9.0 i see
```
test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithFork) ... Could not retrieve traceback for timed out process: 0
Could not retrieve traceback for timed out process: 1
Could not retrieve traceback for timed out process: 2
Timing out after 600 seconds and killing subprocesses.
ERROR
```
and
```
======================================================================
ERROR: test_ddp_model_diff_across_ranks (__main__.TestDistBackendWithFork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 391, in wrapper
    self._join_processes(fn)
  File "/local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 581, in _join_processes
    self._check_no_test_errors(elapsed_time)
  File "/local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 598, in _check_no_test_errors
    raise RuntimeError('Process {} timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 0 timed out after 600.0600988864899 seconds

======================================================================
ERROR: test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithFork)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 391, in wrapper
    self._join_processes(fn)
  File "/local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 583, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 631, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 0 terminated or timed out after 615.1103746891022 seconds
```
and
```
======================================================================
ERROR: test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 391, in wrapper
    self._join_processes(fn)
  File "/local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 583, in _join_processes
    self._check_return_codes(elapsed_time)
  File "/local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py", line 631, in _check_return_codes
    raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
RuntimeError: Process 0 terminated or timed out after 615.0748069286346 seconds
```
----

I also see this;
```
test_ddp_model_diff_across_ranks (__main__.TestDistBackendWithFork) ... [E ProcessGroupNCCL.cpp:566] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=5000) ran for 7996 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:325] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=5000) ran for 7996 milliseconds before timing out.
SIGABRT(6), PID: 39334, Thread 39334:
 frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x44 (0x2b351de4ce74 in /local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xf630 (0x2b34c962a630 in /lib64/libpthread.so.0)
frame #2: write + 0x2d (0x2b34c96296fd in /lib64/libpthread.so.0)
<omitting python frames>

SIGABRT(6), PID: 39334, Thread 39340:
 frame #0: c10::FatalSignalHandler::stacktraceSignalHandler(bool) + 0x44 (0x2b351de4ce74 in /local/tmp.94788/eb-19cx1ygu/tmp49thagy7/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xf630 (0x2b34c962a630 in /lib64/libpthread.so.0)
frame #2: __poll + 0x2d (0x2b34c9b2dccd in /lib64/libc.so.6)
frame #3: <unknown function> + 0x2cbbf1 (0x2b366e112bf1 in /lib64/libcuda.so.1)
frame #4: <unknown function> + 0x27d26a (0x2b366e0c426a in /lib64/libcuda.so.1)
frame #5: <unknown function> + 0x2c39a6 (0x2b366e10a9a6 in /lib64/libcuda.so.1)
frame #6: <unknown function> + 0x7ea5 (0x2b34c9622ea5 in /lib64/libpthread.so.0)
frame #7: clone + 0x6d (0x2b34c9b389fd in /lib64/libc.so.6)

Encountered error while trying to get traceback for process 0: [Errno 32] Broken pipe
Timing out after 600 seconds and killing subprocesses.
```

**Comment by Flamefire** [comment]
@boegel No real idea. However that tests uses 2 different profilers. I.e. `profile()` and `_profile()`: https://github.com/pytorch/pytorch/blob/839eaa2e91556ecd4532596b4fef18a1c3f6e1c1/test/test_profiler.py#L16-L18

Maybe search for every `with _profile` and `with profile` and prepend that `with ...: pass` there with the right profile/_profile?

**Comment by boegel** [comment]
Haven't seen this issue pop up recently, I think it's safe to assume that this was triggered by a bug in the CUDA drivers...
