### ISSUE TITLE
"[Errno 22] Invalid argument" in an easyblock while doing os.readlink

### ISSUE THREAD

**Issue by Poshi** [easybuilders/easybuild-easyconfigs#15706]
Trying to build Boost 1.79.0 with GCCcore 12.1.0 I run into an error from an easyblock itself:
```
$ eb -r . --prefix=/software/pbt Boost-1.79.0-GCCcore-12.1.0.eb
== Temporary log file in case of crash /tmp/eb-o8fcazs8/easybuild-yyfiikvr.log
== found valid index for /software/pbt/software/EasyBuild/4.5.5/easybuild/easyconfigs, so using it...
== resolving dependencies ...
== processing EasyBuild easyconfig /home/groups/pbt/jcamps/tmp/Boost-1.79.0-GCCcore-12.1.0.eb
== building and installing Boost/1.79.0-GCCcore-12.1.0...
== fetching files...
== creating build dir, resetting environment...
== ... (took 1 min 27 secs)
== unpacking...
== ... (took 3 mins 52 secs)
== patching...
== preparing...
== configuring...
== ... (took 20 secs)
== building...
== ... (took 1 min 36 secs)
== testing...
== installing...
== ... (took 2 mins 15 secs)
ERROR: Traceback (most recent call last):
  File "/software/pbt/software/EasyBuild/4.5.5/lib/python3.6/site-packages/easybuild/main.py", line 128, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/software/pbt/software/EasyBuild/4.5.5/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 4058, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/software/pbt/software/EasyBuild/4.5.5/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3941, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/software/pbt/software/EasyBuild/4.5.5/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3776, in run_step
    step_method(self)()
  File "/software/pbt/software/EasyBuild/4.5.5/lib/python3.6/site-packages/easybuild/easyblocks/b/boost.py", line 311, in install_step
    use_abspath_source=False)
  File "/software/pbt/software/EasyBuild/4.5.5/lib/python3.6/site-packages/easybuild/tools/filetools.py", line 329, in symlink
    symlink_target_path = os.path.abspath(os.readlink(symlink_path))
OSError: [Errno 22] Invalid argument: '/software/pbt/software/Boost/1.79.0-GCCcore-12.1.0/lib/libboost_contract.so.1.79.0'
```

The easyconfig used contained:
```
##
# Authors::   Denis Kristak <[thenis@inuits.eu](mailto:thenis@inuits.eu)>
##
name = 'Boost'
version = '1.79.0'
homepage = 'https://www.boost.org/'
description = """Boost provides free peer-reviewed portable C++ source libraries."""
toolchain = {'name': 'GCCcore', 'version': '12.1.0'}
toolchainopts = {'pic': True}
source_urls = ['https://boostorg.jfrog.io/artifactory/main/release/%(version)s/source/']
sources = ['%%(namelower)s_%s.tar.gz' % '_'.join(version.split('.'))]
checksums = ['273f1be93238a068aba4f9735a4a2b003019af067b9c183ed227780b8f36062c']
dependencies = [
    ('bzip2', '1.0.8'),
    ('zlib', '1.2.12'),
    ('XZ', '5.2.5'),
    ('ICU', '71.1'),
]
configopts = '--without-libraries=python,mpi'
# disable MPI, build Boost libraries with tagged layout
boost_mpi = False
tagged_layout = True
moduleclass = 'devel'
```

It was based on the newest easyconfig for Boost found in the repository (Boost-1.79.0-GCC-11.3.0.eb). I modified it to switch versions to the newest ones and to change the toolchain to the desired target.

**Comment by Poshi** [comment]
After a lot of testing and discussion in Slack, we managed to see that I switched from GCC toolchain to GCCcore, but I didn't add the usually needed binutils dependency.
Adding `builddependencies = [('binutils', '2.38')]` to the easyconfig solved the issue and the build have been able to finish.
