### ISSUE TITLE
BLIS-0.9.0-GCC-11.3.0.eb fails on A64FX

### ISSUE THREAD

**Issue by agemuend** [easybuilders/easybuild-easyconfigs#16514]
BLIS fails to build on A64FX apparently because of conflicting flags:

```
Compiling obj/a64fx/testsuite/test_addm.o
cc1: warning: switch -mcpu=a64fx+sha2 conflicts with -march=armv8-a+sve switch
Compiling obj/a64fx/testsuite/test_addv.o
cc1: warning: switch -mcpu=a64fx+sha2 conflicts with -march=armv8-a+sve switch
```

**Comment by agemuend** [comment]
```
(gdb) bt
#0  0x0000000000440ea4 in bli_cntx_init_a64fx._omp_fn ()
#1  0x0000ffffbe5f91cc in gomp_thread_start () from /lib64/libgomp.so.1
#2  0x0000ffffbe677898 in start_thread () from /lib64/libpthread.so.0
#3  0x0000ffffbe531ddc in thread_start () from /lib64/libc.so.6
(gdb) x/i $pc
=> 0x440ea4 <bli_cntx_init_a64fx._omp_fn.0+4>:  msr     s3_3_c11_c8_2, x0
(gdb) disassemble
Dump of assembler code for function bli_cntx_init_a64fx._omp_fn.0:
   0x0000000000440ea0 <+0>:     mov     x0, #0x310                      // #784
=> 0x0000000000440ea4 <+4>:     msr     s3_3_c11_c8_2, x0
   0x0000000000440ea8 <+8>:     mov     x0, #0x1c09                     // #7177
   0x0000000000440eac <+12>:    msr     s3_3_c15_c8_2, x0
   0x0000000000440eb0 <+16>:    ret
End of assembler dump.
```

It seems this is called here to set cache sizes: 

https://github.com/flame/blis/blob/master/config/a64fx/bli_cntx_init_a64fx.c#L108
https://github.com/flame/blis/blob/master/config/a64fx/bli_a64fx_sector_cache.h#L76
