### ISSUE TITLE
deap 1.3.1 on SciPy-Bundle 2022a and 2022.05 is broken

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyconfigs#17411]
```python
Python 3.10.4 (main, Feb 23 2023, 11:12:36) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>  from deap import base
  File "<stdin>", line 1
    from deap import base
IndentationError: unexpected indent
>>> from deap import base
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/easybuild/2020/software/SciPy-bundle/2022.05-foss-2022a/lib/python3.10/site-packages/deap/base.py", line 192
    raise TypeError, ("Both weights and assigned values must be a "
                   ^
SyntaxError: invalid syntax
```

version 1.3.3 works

**Comment by surak** [comment]
I suggest the patch

```patch
--- SciPy-bundle-2022.05-foss-2022a.eb.orig	2023-02-23 12:38:50.865947370 +0000
+++ SciPy-bundle-2022.05-foss-2022a.eb	2023-02-23 12:39:53.355146929 +0000
@@ -31,13 +31,13 @@
         ],
         'sources': ['%(name)s-%(version)s.zip'],
         'checksums': [
-            'dbc7601a3b7472d559dc7b933b18b4b66f9aa7452c120e87dfb33d02008c8a18',  # numpy-1.22.3.zip
-            # numpy-1.20.3_disable_fortran_callback_test.patch
-            '44975a944544fd0e771b7e63c32590d257a3713070f8f7fdf60105dc516f1d75',
-            # numpy-1.22.3_disable-broken-override-test.patch
-            '9c589bb073b28b25ff45eb3c63c57966aa508dd8b318d0b885b6295271e4983c',
-            # numpy-1.22.3_skip-ppc-long-complex-test.patch
-            '058c8128b9f7158b4d5bedb2f52ccc7e1362b99c352c3d10335f98a6194c880e',
+            {'numpy-1.22.3.zip': 'dbc7601a3b7472d559dc7b933b18b4b66f9aa7452c120e87dfb33d02008c8a18'},
+            {'numpy-1.20.3_disable_fortran_callback_test.patch':
+             '44975a944544fd0e771b7e63c32590d257a3713070f8f7fdf60105dc516f1d75'},
+            {'numpy-1.22.3_disable-broken-override-test.patch':
+             '9c589bb073b28b25ff45eb3c63c57966aa508dd8b318d0b885b6295271e4983c'},
+            {'numpy-1.22.3_skip-ppc-long-complex-test.patch':
+             '058c8128b9f7158b4d5bedb2f52ccc7e1362b99c352c3d10335f98a6194c880e'},
         ],
     }),
     ('ply', '3.11', {
@@ -53,8 +53,6 @@
         'checksums': ['0b2cba712e09f7630879dff69f268460bfe34a6d6000451b47d598558a92a875'],
     }),
     ('scipy', '1.8.1', {
-        # compilation with Pythran enabled fails when using Intel compilers,
-        # see https://github.com/scipy/scipy/issues/14935
         'prebuildopts': "export SCIPY_USE_PYTHRAN=0 && ",
         'preinstallopts': "export SCIPY_USE_PYTHRAN=0 && ",
         'checksums': ['9e3fb1b0e896f14a85aa9a28d5f755daaeeb54c897b746df7a55ccb02b340f33'],
@@ -75,12 +73,8 @@
     ('mpmath', '1.2.1', {
         'checksums': ['79ffb45cf9f4b101a807595bcb3e72e0396202e0b1d25d689134b48c4216a81a'],
     }),
-    ('deap', '1.3.1', {
-        'patches': ['deap-1.3.1_no_2to3.patch'],
-        'checksums': [
-            '11f54493ceb54aae10dde676577ef59fc52d52f82729d5a12c90b0813c857a2f',  # deap-1.3.1.tar.gz
-            '3fa9fac74b0750ac6667371ce0634c797d62d270c76eee9c258b55f4a5a5e689',  # deap-1.3.1_no_2to3.patch
-        ],
+    ('deap', '1.3.3', {
+        'checksums': ['8772f1b0fff042d5e516b0aebac2c706243045aa7d0de8e0b8658f380181cf31'],
     }),
 ]
```

The extra lines are an artifact of `eb --inject-checksums` - It changes the checksums and deletes comments.
