### ISSUE TITLE
PyTorch-1.12.1-foss-2021b-CUDA-11.5.2 test failures `test_native_mha` and `distributed/fsdp/test_fsdp_core`

### ISSUE THREAD

**Issue by casparvl** [easybuilders/easybuild-easyconfigs#17615]
We don't know too much about these test failures, but they happened for @Flamefire (`distributed/fsdp/test_fsdp_core`) and @branfosj (`test_native_mha`). The latter only fails on Broadwell.

We don't want to block PR https://github.com/easybuilders/easybuild-easyconfigs/pull/17272 any longer over this, so we've logged the issue here, and can track any progress here. In the meantime, we'll merge the PR since it probably works for a reasonable amount of people, and thus we want to get it out there (preferably before the toolchain is deprecated :)).

**Comment by boegel** [comment]
@branfosj @Flamefire Can you hunt down more details on these test failures, and share the relevant output verbatim in this issue?

**Comment by boegel** [comment]
In my test report for https://github.com/easybuilders/easybuild-easyconfigs/pull/17272, I ran into the following failures:

```
distributed/elastic/multiprocessing/api_test failed!
test_quantization failed!
```

Details on these failing tests are missing from the log included in the test report though...

**Comment by boegel** [comment]
More info on `test_quantization`:

```
ERROR: test_qnnpack_add (quantization.core.test_quantized_op.TestQNNPackOps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/easybuild_build/PyTorch/1.12.1/foss-2021b/pytorch-v1.12.1/test/quantization/core/test_quantized_op.py", line 5573, in test_qnnpack_add
    @given(A=hu.tensor(shapes=hu.array_shapes(1, 5, 1, 5),
  File "/software/hypothesis/6.14.6-GCCcore-11.2.0/lib/python3.9/site-packages/hypothesis/core.py", line 1180, in wrapped_test
    raise the_error_hypothesis_found
  File "/software/hypothesis/6.14.6-GCCcore-11.2.0/lib/python3.9/site-packages/hypothesis/core.py", line 1145, in wrapped_test
    state.run_engine()
  File "/software/hypothesis/6.14.6-GCCcore-11.2.0/lib/python3.9/site-packages/hypothesis/core.py", line 769, in run_engine
    runner.run()
  File "/software/hypothesis/6.14.6-GCCcore-11.2.0/lib/python3.9/site-packages/hypothesis/internal/conjecture/engine.py", line 495, in run
    self._run()
  File "/software/hypothesis/6.14.6-GCCcore-11.2.0/lib/python3.9/site-packages/hypothesis/internal/conjecture/engine.py", line 897, in _run
    self.generate_new_examples()
  File "/software/hypothesis/6.14.6-GCCcore-11.2.0/lib/python3.9/site-packages/hypothesis/internal/conjecture/engine.py", line 748, in generate_new_examples
    self.test_function(data)
  File "/software/hypothesis/6.14.6-GCCcore-11.2.0/lib/python3.9/site-packages/hypothesis/internal/conjecture/engine.py", line 328, in test_function
    self.record_for_health_check(data)
  File "/software/hypothesis/6.14.6-GCCcore-11.2.0/lib/python3.9/site-packages/hypothesis/internal/conjecture/engine.py", line 407, in record_for_health_check
    fail_health_check(
  File "/software/hypothesis/6.14.6-GCCcore-11.2.0/lib/python3.9/site-packages/hypothesis/internal/healthcheck.py", line 32, in fail_health_check
    raise FailedHealthCheck(message, label)
hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 3 valid examples in 1.14 seconds (13 invalid ones and 0 exceeded maximum size). Try decreasing size of the data you're generating (with e.g.max_size or max_leaves parameters).
See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.too_slow to the suppress_health_check settings for this test.

----------------------------------------------------------------------
Ran 877 tests in 2226.414s

FAILED (errors=1, skipped=75)
test_quantization failed!
```

**Comment by branfosj** [comment]
We can try suppressing that. Not sure if it just needs more time or there is a bigger issue.

See https://github.com/pytorch/pytorch/blob/951df11af89162b23a7e995a0c14cd6030755e54/test/quantization/core/test_quantized_op.py#L6454
```py
@settings(suppress_health_check=(HealthCheck.filter_too_much,))
```
to
```py
@settings(suppress_health_check=(HealthCheck.filter_too_much, HealthCheck.too_slow))
```

**Comment by sassy-crick** [comment]
Well, I got the same issue it seems on `Rome` and `RTX6000`
```
Running test_native_mha ... [2023-03-29 20:13:22.345522]
Executing ['/sw-eb/software/Python/3.10.4-GCCcore-11.3.0/bin/python', 'test_native_mha.py', '-v'] ... [2023-03-29 20:13:22.345617]
test_native_multihead_attention_cpu_float32 (__main__.TestMHADeviceTypeCPU) ... ok
test_native_multihead_encoder_decoder_attention_cpu_float32 (__main__.TestMHADeviceTypeCPU) ... ok
test_native_multihead_self_attention_cpu_float32 (__main__.TestMHADeviceTypeCPU) ... /dev/shm/hpcsw/PyTorch/1.12.1/foss-2022a-CUDA-11.7.0/pytorch-v1.12.1/test/test_native_mha.py:191: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at  /dev/shm/hpcsw/PyTorch/1.12.1/foss-2022a-CUDA-11.7.0/pytorch-v1.12.1/aten/src/ATen/NestedTensorImpl.cpp:50.)
  q = torch.nested_tensor(qs, device=device, dtype=dtype)
test_transform_bias_rescale_qkv_cpu_float32 (__main__.TestMHADeviceTypeCPU) ... ok
test_transform_bias_rescale_qkv_nested_cpu_float32 (__main__.TestMHADeviceTypeCPU) ... skipped 'Only runs on cuda'

======================================================================
FAIL: test_native_multihead_self_attention_cpu_float32 (__main__.TestMHADeviceTypeCPU) (use_padding=False, pad_all=False, use_nt=False, need_weights=False, average_attn_weights=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/hpcsw/PyTorch/1.12.1/foss-2022a-CUDA-11.7.0/pytorch-v1.12.1/test/test_native_mha.py", line 263, in test_native_multihead_self_attention
    self._test_multihead_attention_impl(
  File "/dev/shm/hpcsw/PyTorch/1.12.1/foss-2022a-CUDA-11.7.0/pytorch-v1.12.1/test/test_native_mha.py", line 241, in _test_multihead_attention_impl
    torch.testing.assert_close(ypt, ynpt, atol=2e-5, rtol=2e-3)
  File "/dev/shm/hpcsw/eb-5ayehsoe/tmpa6j95d73/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1344, in assert_close
    assert_equal(
  File "/dev/shm/hpcsw/eb-5ayehsoe/tmpa6j95d73/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 8192 (0.0%)
Greatest absolute difference: 2.092123031616211e-05 at index (12, 7, 6) (up to 2e-05 allowed)
Greatest relative difference: 0.09903364604641321 at index (12, 7, 6) (up to 0.002 allowed)
```
That was the only failing test. I am currently building it on `Skylake` with the same GPU and will report back when it is done. 

----------------------------------------------------------------------
