### ISSUE TITLE
PyTorch-1.12.1-foss-2022a-CUDA-11.7.0.eb test failures: test_wishart_log_prob

### ISSUE THREAD

**Issue by ysagon** [easybuilders/easybuild-easyconfigs#18060]
Hi,

I had an error during the test step:

```
======================================================================
FAIL: test_wishart_log_prob (__main__.TestDistributions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dev/shm/ebbuild/PyTorch/1.12.1/foss-2022a-CUDA-11.7.0/pytorch-v1.12.1/test/distributions/test_distributions.py", line 2334, in test_wishart_log_prob
    self.assertEqual(batched_prob, unbatched_prob, atol=1e-3, rtol=0)
  File "/tmp/eb-s485x9uu/tmprmf7m0qx/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2219, in assertEqual
    assert_equal(
  File "/tmp/eb-s485x9uu/tmprmf7m0qx/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 3 / 5000 (0.1%)
Greatest absolute difference: inf at index (303, 1) (up to 0.001 allowed)
Greatest relative difference: nan at index (303, 1) (up to 0 allowed)

----------------------------------------------------------------------
```

**Comment by ysagon** [comment]
I tried on an A100 GPU as well, same.

**Comment by Micket** [comment]
I recommend testing with your container as well, to see if this is related to how EB has built pytorch, or just one more of the many issues with torch itself.
