### ISSUE TITLE
PyTorch-Geometric will fail on gpu nodes if installed from CPU nodes

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyconfigs#18274]
If you install it by default it tries to detect if the node has a gpu or not. If it doesn't, it installs without gpu support.

When you run it into a gpu node, it will fail:

```
srun -A jscbenchmark --nodes=1 --partition=develbooster --pty /bin/bash
srun: job 8022071 queued and waiting for resources
srun: job 8022071 has been allocated resources
bash-4.4$ module load Stages/2023  GCC/11.3.0  OpenMPI/4.1.4 PyTorch/1.12.0-CUDA-11.7 PyTorch-Geometric/2.1.0-PyTorch-1.12.0-CUDA-11.7
bash-4.4$ python
Python 3.10.4 (main, Oct  4 2022, 08:48:24) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch_spline_conv import spline_conv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/software/juwelsbooster/stages/2023/software/PyTorch-Geometric/2.1.0-foss-2022a-PyTorch-1.12.0-CUDA-11.7/lib/python3.10/site-packages/torch_spline_conv/__init__.py", line 12, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'
>>> 
```

The solution is to use a `FORCE_CUDA=1`

**Comment by surak** [comment]
The same is true for torch_sparse by the way
