### ISSUE TITLE
Tkinter does not work in GCCcore/12.3.0

### ISSUE THREAD

**Issue by schiotz** [easybuilders/easybuild-easyconfigs#18858]
Tkinter does not seem to work with the new foss/2023a (GCCcore/12.3.0) toolchain.  Neither matplotlib nor our own gui works, they both fail with the error:

_tkinter.TclError: Can't find a usable tk.tcl in the following directories:
    /home/niflheim/schiotz/easybuild_2023a/skylake/software/Tcl/8.6.13-GCCcore-12.3.0/lib/tcl8.6/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Tcl/8.6.13-GCCcore-12.3.0/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/library

Simple test script (requires that `$MPLBACKEND` is manually unset to reenable the gui):

```
import matplotlib.pyplot as plt
plt.plot([0,1], [0,1])
plt.show()
```

It crashes with the error above with `matplotlib/3.7.2-gfbf-2023a` but works with earlier toolchains.  However, the problem is not in matplotlib as the same error occurs in other programs trying to use TKinter.

**Comment by Flamefire** [comment]
I wasn't able to reproduce this on PPC:
```
module load "matplotlib/3.7.2-gfbf-2023a"
unset MPLBACKEND
python -c 'import matplotlib.pyplot as plt; plt.plot([0,1], [0,1]); plt.show()'
```

I found the mentioned file in `software/Tk/8.6.13-GCCcore-12.3.0/lib/tk8.6/tk.tcl`

I'm wondering how it determines the search path you see, i.e.

- /home/niflheim/schiotz/easybuild_2023a/skylake/software/Tcl/8.6.13-GCCcore-12.3.0/lib/tcl8.6/tk8.6
- /home/niflheim/schiotz/easybuild_2023a/skylake/software/Tcl/8.6.13-GCCcore-12.3.0/lib/tk8.6
- /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/tk8.6
- /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/tk8.6
- /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/lib/tk8.6
- /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/library

Does your environment contain any variable that can explain this? Does `python -c "import tkinter"` work? Is there more of the error message, like a stack trace?

I also found https://github.com/NixOS/nixpkgs/issues/234962
It suggest that `export TK_LIBRARY="$EBROOTTK/lib/tk8.6"` or similar might help

**Comment by schiotz** [comment]
Thank you @Flamefire at least I have a workaround for now.  Setting ``TK_LIBRARY="$EBROOTTK/lib/tk8.6"`` makes it work.  I am not setting anything related in my environment that could affect the search path.  But there is a change in the Tk easybuild between ``Tk-8.6.12-GCCcore-12.2.0.eb`` and ``Tk-8.6.13-GCCcore-12.3.0.eb``: The patch [Tk-8.6.4_different-prefix-with-tcl.patch](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/t/Tk/Tk-8.6.4_different-prefix-with-tcl.patch) is no longer applied, and it looks like it could be relevant.

Anyway, the full stacktrace is below:

```
10:14 [svol] ~$ python -c 'import matplotlib.pyplot as plt; plt.plot([0,1], [0,1]); plt.show()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/pyplot.py", line 2812, in plot
    return gca().plot(
           ^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/pyplot.py", line 2309, in gca
    return gcf().gca()
           ^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/pyplot.py", line 906, in gcf
    return figure()
           ^^^^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/pyplot.py", line 840, in figure
    manager = new_figure_manager(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/pyplot.py", line 384, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 3574, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 3579, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 1742, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/matplotlib/3.7.2-gfbf-2023a/lib/python3.11/site-packages/matplotlib/backends/_backend_tk.py", line 483, in create_with_canvas
    window = tk.Tk(className="matplotlib")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/niflheim/schiotz/easybuild_2023a/skylake/software/Tkinter/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages/tkinter/__init__.py", line 2326, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    /home/niflheim/schiotz/easybuild_2023a/skylake/software/Tcl/8.6.13-GCCcore-12.3.0/lib/tcl8.6/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Tcl/8.6.13-GCCcore-12.3.0/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/lib/tk8.6 /home/niflheim/schiotz/easybuild_2023a/skylake/software/Python/3.11.3-GCCcore-12.3.0/library



This probably means that tk wasn't installed properly.
```

**Comment by Flamefire** [comment]
Yes that looks like exactly the issue. I've seen that patch (or better: the change) mentioned in the linked discussion and the commit message of the patch is clear that it is supposed to fix your issue.

It seems it was omitted from the new version because the source changed and the patch didn't apply cleanly anymore. I ported the patch to 8.6.13 and created a PR. Can you test if it works with https://github.com/easybuilders/easybuild-easyconfigs/pull/18864 (`eb --from-pr 18864 --rebuild`)

**Comment by schiotz** [comment]
Thank you very much, @Flamefire, now it works!
