### ISSUE TITLE
Loading Python-bundle-PyPI causes EasyBuild to crash

### ISSUE THREAD

**Issue by schiotz** [easybuilders/easybuild-easyconfigs#19111]
Hi,

This is not a serious issue, as one should never have loaded modules while building with EasyBuild, but loading ``Python-bundle-PyPI/2023.06-GCCcore-12.3.0`` causes EasyBuild to crash instead of issuing a warning against having loaded module and quitting peacefully.

```
10:38 [surt] tmp$ module purge
10:38 [surt] tmp$ module load EasyBuild
10:38 [surt] tmp$ eb --version
This is EasyBuild 4.8.2 (framework: 4.8.2, easyblocks: 4.8.2) on host surt.xxxxxxx.
10:38 [surt] tmp$ module load Python/3.11.3-GCCcore-12.3.0
10:38 [surt] tmp$ eb --version
This is EasyBuild 4.8.2 (framework: 4.8.2, easyblocks: 4.8.2) on host surt.xxxxxxx.
10:38 [surt] tmp$ module load Python-bundle-PyPI/2023.06-GCCcore-12.3.0
10:38 [surt] tmp$ eb --version
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/modules/software/EasyBuild/4.8.2/lib/python3.6/site-packages/easybuild/main.py", line 50, in <module>
    from easybuild.tools.build_log import EasyBuildError, print_error, print_msg, print_warning, stop_logging
  File "/home/modules/software/EasyBuild/4.8.2/lib/python3.6/site-packages/easybuild/tools/build_log.py", line 46, in <module>
    from easybuild.tools.version import VERSION, this_is_easybuild
  File "/home/modules/software/EasyBuild/4.8.2/lib/python3.6/site-packages/easybuild/tools/version.py", line 77, in <module>
    git_rev = get_git_revision()
  File "/home/modules/software/EasyBuild/4.8.2/lib/python3.6/site-packages/easybuild/tools/version.py", line 60, in get_git_revision
    from git import Git, GitCommandError
  File "/home/niflheim/schiotz/.local/lib/python3.6/site-packages/git/__init__.py", line 8, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/niflheim/schiotz/.local/lib/python3.6/site-packages/git/exc.py", line 10, in <module>
    from git.compat import safe_decode
  File "/home/niflheim/schiotz/.local/lib/python3.6/site-packages/git/compat.py", line 32, in <module>
    from git.types import TBD
  File "/home/niflheim/schiotz/.local/lib/python3.6/site-packages/git/types.py", line 13, in <module>
    from typing_extensions import (Final, Literal, SupportsIndex,                           # noqa: F401
  File "/home/modules/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0/lib/python3.11/site-packages/typing_extensions.py", line 210, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'
```

(hostname censored due to paranoia).

Edit: The issue was also present with the previous version of EasyBuild.

**Comment by Micket** [comment]
Loading a python module will put things into PYTHONPATH, and i think should be expected to break things that aren't strictly compatible with it.
In this case, it breaks python3.6 (which uses the dependencies from your home dir:
```
/home/niflheim/schiotz/.local/lib/python3.6/site-packages/git/types.py
```

Similar things could happen with LD_LIBRARY_PATH and other environment changes that comes from loading a module. I don't think there is anything we could ever do about this.

**Comment by schiotz** [comment]
Yes, the dependency from .local was to make EasyBuild git integration work, but it makes sense that a newer version of that package would break with python 3.6.

I guess this is just unavoidable.  I just did not see it previously, and thought it was a relatively new issue with EasyBuild - I guess it was really triggered by me setting EB_PYTHON to move away from Python 2.7.

I'll close this issue again, then.
