### ISSUE TITLE
gem won't work for Ruby/3.2.2-GCCcore-12.2.0 unless zlib/1.2.12-GCCcore-12.2.0 is also loaded

### ISSUE THREAD

**Issue by cjroberts** [easybuilders/easybuild-easyconfigs#19335]
Hello, I have found that `gem` won't work for `Ruby/3.2.2-GCCcore-12.2.0` unless `zlib/1.2.12-GCCcore-12.2.0` is also loaded. Some gems also won't build unless `GCC/12.2.0` is loaded, for example, `rmagick`, the Ruby bindings to ImageMagick.

To reproduce the first issue:

```
module load Ruby/3.2.2-GCCcore-12.2.0
gem install --install-dir /path/to/install/dir aspera-cli
```

Resulting in:
```
Fetching rexml-3.2.6.gem
<internal:/gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/x86_64-linux/zlib.so) - /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/x86_64-linux/zlib.so (LoadError)
        from <internal:/gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/package.rb:196:in `initialize'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/package.rb:161:in `new'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/package.rb:161:in `new'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/installer.rb:113:in `at'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/resolver/specification.rb:100:in `install'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:279:in `block in install_into'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:271:in `each'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:271:in `install_into'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:147:in `install'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:214:in `install_gem'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `install_gems'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:169:in `execute'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/command.rb:327:in `invoke_with_build_args'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/command_manager.rb:192:in `process_args'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/command_manager.rb:150:in `run'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
        from /apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/bin/gem:10:in `<main>'
```

To reproduce the second:

```
module load zlib/1.2.12-GCCcore-12.2.0
module load Ruby/3.2.2-GCCcore-12.2.0
module load ImageMagick/7.1.0-53-GCCcore-12.2.0
gem install --install-dir /path/to/install/dir rmagick
```

The resulting error is:

```
Fetching pkg-config-1.5.6.gem                                                                                                                   [24/570]
Successfully installed pkg-config-1.5.6
Fetching rmagick-5.3.0.gem
Building native extensions. This could take a while...
ERROR:  Error installing rmagick:
        ERROR: Failed to build gem native extension.

    current directory: /path/to/install/dir/gems/rmagick-5.3.0/ext/RMagick
/gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/bin/ruby extconf.rb
checking for brew... no
checking for pacman... no
checking for Ruby version >= 2.3.0... yes
checking for forced use of ImageMagick 6... no
checking for outdated ImageMagick version (<= 6.7.7)... no
checking for gcc... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/bin/$(RUBY_BASE_NAME)
        --with-pkg-config
        --without-pkg-config
        --with-override-variables
        --without-override-variables
/gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/mkmf.rb:490:in `try_do': The compiler failed to generate an executable
file. (RuntimeError)
You have to install development tools first.

        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/mkmf.rb:583:in `try_link0'
        from /gpfs3/apps/eb/2022b/ivybridge/software/Ruby/3.2.2-GCCcore-12.2.0/lib/ruby/3.2.0/mkmf.rb:601:in `try_link'
        from extconf.rb:109:in `configure_compile_options'
        from extconf.rb:47:in `initialize'
        from extconf.rb:442:in `new'
        from extconf.rb:442:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /path/to/install/dir/extensions/x86_64-linux/3.2.0/rmagick-5.3.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /path/to/install/dir/gems/rmagick-5.3.0 for inspection.
Results logged to /path/to/install/dir/extensions/x86_64-linux/3.2.0/rmagick-5.3.0/gem_make.out
```

This is solved by `module load GCC/12.2.0` before the `gem install` command.

Would it be reasonable to package Ruby with `zlib` and `GCC` so that `gem` will work right away?

**Comment by Micket** [comment]
scanning through all the linking done by ruby i found zlib, libyaml, openssl, and binutils is needed for the compiler (via gem). All of these should be dependencies. Fix is in #20214
