### ISSUE TITLE
Arrow-14.0.1-gfbf-2023a build fails: python package shows version 0.0.0

### ISSUE THREAD

**Issue by kverstae** [easybuilders/easybuild-easyconfigs#19849]
I am trying to build Arrow-14.0.1-gfbf-2023a, but running into some issues. The package `pyarrow` seems to have been installed, but doesn't report any version (or version 0.0.0) making the build fail.

The build logs look like this:
```
== 2024-02-14 14:03:44,823 run.py:247 INFO running cmd: python -c 'import pyarrow' 
== 2024-02-14 14:03:45,112 easyblock.py:3632 INFO sanity check command python -c 'import pyarrow' ran successfully! (output: )
== 2024-02-14 14:03:45,113 run.py:247 INFO running cmd: python -c 'import pyarrow.dataset' 
== 2024-02-14 14:03:45,478 easyblock.py:3632 INFO sanity check command python -c 'import pyarrow.dataset' ran successfully! (output: Traceback (most recent call last):
  File "pyarrow/pandas-shim.pxi", line 104, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow/pandas-shim.pxi", line 48, in pyarrow.lib._PandasAPIShim._import_pandas
  File "/usr/local/modules/eb.el9/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/modules/eb.el9/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/pandas/compat/__init__.py", line 29, in <module>
    from pandas.compat.pyarrow import (
  File "/usr/local/modules/eb.el9/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 11, in <module>
    _palv = Version(_pa_version)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/modules/eb.el9/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/pandas/util/version/__init__.py", line 336, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
Exception ignored in: 'pyarrow.lib._PandasAPIShim._have_pandas_internal'
Traceback (most recent call last):
  File "pyarrow/pandas-shim.pxi", line 104, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow/pandas-shim.pxi", line 48, in pyarrow.lib._PandasAPIShim._import_pandas
  File "/usr/local/modules/eb.el9/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/modules/eb.el9/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/pandas/compat/__init__.py", line 29, in <module>
    from pandas.compat.pyarrow import (
  File "/usr/local/modules/eb.el9/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 11, in <module>
    _palv = Version(_pa_version)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/modules/eb.el9/software/SciPy-bundle/2023.07-gfbf-2023a/lib/python3.11/site-packages/pandas/util/version/__init__.py", line 336, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
)
== 2024-02-14 14:03:45,479 run.py:247 INFO running cmd: python -c 'import pyarrow.parquet' 
== 2024-02-14 14:03:45,704 easyblock.py:3632 INFO sanity check command python -c 'import pyarrow.parquet' ran successfully! (output: )
== 2024-02-14 14:03:45,704 environment.py:93 INFO Environment variable PYTHONNOUSERSITE set to 1 (previously undefined)
== 2024-02-14 14:03:45,704 pythonpackage.py:969 INFO Detection of downloaded depenencies enabled, checking output of installation command...
== 2024-02-14 14:03:45,705 pythonpackage.py:229 INFO Determining pip version...
== 2024-02-14 14:03:45,705 run.py:247 INFO running cmd: /usr/local/modules/eb.el9/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip --version 
== 2024-02-14 14:03:46,071 pythonpackage.py:237 INFO Found pip version: 23.1.2
== 2024-02-14 14:03:46,072 run.py:247 INFO running cmd: /usr/local/modules/eb.el9/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip check 
== 2024-02-14 14:03:47,443 pythonpackage.py:1037 INFO `/usr/local/modules/eb.el9/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip check` completed successfully
== 2024-02-14 14:03:47,443 pythonpackage.py:555 INFO Running command '/usr/local/modules/eb.el9/software/Python/3.11.3-GCCcore-12.3.0/bin/python -m pip list --isolated --disable-pip-version-check --format json'
== 2024-02-14 14:03:48,185 pythonpackage.py:1063 INFO Found 1 invalid packages out of 151 packages
== 2024-02-14 14:03:48,205 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): The following Python packages were likely not installed correctly because they show a version of '0.0.0':
pyarrow
This may be solved by using a *-none-any.whl file as the source instead. See e.g. the SOURCE*_WHL templates.
Otherwise you could check if the package provides a version at all or if e.g. poetry is required (check the source for a pyproject.toml and see PEP517 for details on that). (at easybuild/easyblocks/generic/pythonpackage.py:1076 in sanity_check_step)
== 2024-02-14 14:03:48,206 build_log.py:267 INFO ... (took 4 secs)
== 2024-02-14 14:03:48,206 filetools.py:2012 INFO Removing lock /usr/local/modules/eb.el9/software/.locks/_usr_local_modules_eb.el9_software_Arrow_14.0.1-gfbf-2023a.lock...
== 2024-02-14 14:03:48,206 filetools.py:383 INFO Path /usr/local/modules/eb.el9/software/.locks/_usr_local_modules_eb.el9_software_Arrow_14.0.1-gfbf-2023a.lock successfully removed.
== 2024-02-14 14:03:48,207 filetools.py:2016 INFO Lock removed: /usr/local/modules/eb.el9/software/.locks/_usr_local_modules_eb.el9_software_Arrow_14.0.1-gfbf-2023a.lock
== 2024-02-14 14:03:48,207 easyblock.py:4283 WARNING build failed (first 300 chars): The following Python packages were likely not installed correctly because they show a version of '0.0.0':
pyarrow
This may be solved by using a *-none-any.whl file as the source instead. See e.g. the SOURCE*_WHL templates.
Otherwise you could check if the package provides a version at all or if e.g.
== 2024-02-14 14:03:48,207 easyblock.py:328 INFO Closing log for application name Arrow version 14.0.1
```

**Comment by jfgrimm** [comment]
@kverstae this issue was fixed through this PR: https://github.com/easybuilders/easybuild-easyconfigs/pull/19777
Once `Python`, `Python-bundle-PyPI`  and `hatchling` have been rebuilt, you should be able to install Arrow

**Comment by jfgrimm** [comment]
for reference, the `Arrow` easyconfig was recently changed too: https://github.com/easybuilders/easybuild-easyconfigs/pull/19758#issuecomment-1922391584
