### ISSUE TITLE
Permissions problems with Anaconda3/2024.02-1

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#20443]
Several errors like this at the permissions stage:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 190-201: surrogates not allowed
Call stack:
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/apps/eb/2022b/skylake/software/EasyBuild/4.9.1/lib/python3.6/site-packages/easybuild/main.py", line 778, in <module>
    main(prepared_cfg_data=(init_session_state, eb_go, cfg_settings))
  File "/apps/eb/2022b/skylake/software/EasyBuild/4.9.1/lib/python3.6/site-packages/easybuild/main.py", line 734, in main
    hooks, do_build)
  File "/apps/eb/2022b/skylake/software/EasyBuild/4.9.1/lib/python3.6/site-packages/easybuild/main.py", line 566, in process_eb_args
    exit_on_failure=exit_on_failure)
  File "/apps/eb/2022b/skylake/software/EasyBuild/4.9.1/lib/python3.6/site-packages/easybuild/main.py", line 135, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/apps/eb/2022b/skylake/software/EasyBuild/4.9.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 4270, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/apps/eb/2022b/skylake/software/EasyBuild/4.9.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 4149, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/apps/eb/2022b/skylake/software/EasyBuild/4.9.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3984, in run_step
    step_method(self)()
  File "/apps/eb/2022b/skylake/software/EasyBuild/4.9.1/lib/python3.6/site-packages/easybuild/framework/easyblock.py", line 3864, in permissions_step
    adjust_permissions(self.installdir, perms, add=True, recursive=True, relative=True, ignore_errors=True)
  File "/apps/eb/2022b/skylake/software/EasyBuild/4.9.1/lib/python3.6/site-packages/easybuild/tools/filetools.py", line 1812, in adjust_permissions
    _log.debug("Current permissions for %s are already OK: %s", path, oct(current_perms))
Message: 'Current permissions for %s are already OK: %s'
Arguments: ('/apps/eb/2022b/skylake/software/Anaconda3/2024.02-1/pkgs/python-libarchive-c-2.9-pyhd3eb1b0_1/info/test/tests/data/\udced\udc94\udc84\udceb\udca1\udc9c\udcea\udcb7\udcb8\udceb\udc9e\udca8.README', '0o100644')
```

This is on CentOS 7.9 using a build container.

**Comment by Micket** [comment]
As python2 and centos7 is not truly long dead, i think we can close this.
