### ISSUE TITLE
Python system path included in EasyBuild module

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-easyconfigs#5015]
The command `htseq-count --help` fails with the following error:

```
Traceback (most recent call last):
  File "/easybuild/test/software/HTSeq/0.6.1p1-foss-2016b-Python-2.7.12/bin/htseq-count", line 4, in <module>
    __import__('pkg_resources').run_script('HTSeq===0.6.1p1', 'htseq-count')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/easybuild/test/software/HTSeq/0.6.1p1-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/HTSeq-0.6.1p1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/htseq-count", line 3, in <module>
    import HTSeq.scripts.count
  File "/easybuild/test/software/HTSeq/0.6.1p1-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/HTSeq-0.6.1p1-py2.7-linux-x86_64.egg/HTSeq/__init__.py", line 9, in <module>
    from _HTSeq import *
  File "numpy.pxd", line 155, in init HTSeq._HTSeq (src/_HTSeq.c:34392)
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name multiarray
```

The module was build with `eb --buildpath=/dev/shm --optarch=march=corei7 --prefix=/easybuild/test HTSeq-0.6.1p1-foss-2016b-Python-2.7.12.eb -dr` and EasyBuild 3.3.1 on a Ubuntu 16.04.

I suspect there is some Python module missing. The EasyConfig doesn't include `Pysam` or `Numpy` as a dependency, allthough they are listed as dependencies in the HTSeq readme.

*EDIT:* I created an EasyConfig with `Pysam` and `Numpy` as dependencies and there is the same error. There the path to Numpy in `PYTHONPATH` is somehow after the system path so it doesn't load the selfbuild version. When you do `sys.path.reverse()` you can then do `import numpy` just fine. But that's another problem.

**Comment by boegel** [comment]
@SethosII You'll need to make sure `multiarray` is also available, either by including it as a dependency and provided the necessary easyconfig file for it, or by installing `HTSeq` as a bundle, like we also do for `Pysam`, see https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/Pysam/Pysam-0.9.1.4-foss-2016b-Python-2.7.12.eb

**Comment by SethosII** [comment]
@boegel Ok, the EasyConfig I used is an existing one: https://github.com/easybuilders/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/h/HTSeq/HTSeq-0.6.1p1-foss-2016b-Python-2.7.12.eb. So this is more like a bug report, at least it's not working for me. The pull request https://github.com/easybuilders/easybuild-easyconfigs/pull/5020 is my attempt to provide something working, but it isn't right now for the same reason.

`multiarray` already seems to be included but isn't visible for some reason, only after reversing the `PYTHONPATH` variable, also the error says that it looks in the system numpy not the module:

```
> module load Python/2.7.12-foss-2016b # from EasyBuild
> python
Python 2.7.12 (default, Jan 10 2017, 14:06:18) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name multiarray
>>> import sys
>>> sys.path.reverse()
>>> import numpy
>>> # works fine
```

**Comment by boegel** [comment]
@SethosII Thanks for clarifying.

The actual problem is that the numpy from your OS is being picked up (which happens to require `multiarray`), that really shouldn't happen...

What does this print after loading the Python module?

```shell
python -c 'import sys; print sys.path'
```

Can you share what the contents of file at `$EBROOTPYTHON/lib/python2.7/site-packages/setuptools.pth` are? Most likely that's injecting a system location into your Python search path, which leads to Python preferring `numpy` from the OS...

**Comment by SethosII** [comment]
@boegel It turns out that loading `EasyBuild` causes the system path to show up.

Here is the output of `python -c 'import sys; print sys.path'`:

fresh shell, only HTSeq loaded (working):
```
['',
 '/mnt/fhgfs_ribdata/easybuild/test/software/HTSeq/0.9.1-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/HTSeq-0.9.1-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/test/software/Pysam/0.9.1.4-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/matplotlib/1.5.3-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/cycler-0.10.0-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/matplotlib/1.5.3-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/matplotlib-1.5.3-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pyparsing-2.1.5-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pytz-2016.4-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/python_dateutil-2.5.3-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/test/software/Pysam/0.9.1.4-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/Cython-0.25.1-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/setuptools-23.1.0-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/blist-1.3.6-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/Cython-0.24-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/six-1.10.0-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/python_dateutil-2.5.3-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/decorator-4.0.10-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/liac_arff-2.1.0-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/ecdsa-0.13-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/cryptography-1.4-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/ipaddress-1.0.17-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/enum34-1.1.6-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pyasn1-0.1.9-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/idna-2.2-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/paramiko-2.0.1-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pyparsing-2.1.5-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/netifaces-0.10.4-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/funcsigs-1.0.2-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pytz-2016.4-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pandas-0.18.1-py2.7-linux-x86_64.egg',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/virtualenv-15.0.2-py2.7.egg',
 '/mnt/fhgfs_ribdata/easybuild/test/software/HTSeq/0.9.1-foss-2016b-Python-2.7.12/lib/python2.7/site-packages',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/matplotlib/1.5.3-foss-2016b-Python-2.7.12/lib/python2.7/site-packages',
 '/mnt/fhgfs_ribdata/easybuild/test/software/Pysam/0.9.1.4-foss-2016b-Python-2.7.12/lib/python2.7/site-packages',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python27.zip',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/plat-linux2',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/lib-tk',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/lib-old',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/lib-dynload',
 '/mnt/fhgfs_ribdata/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages']
```

after loading EasyBuild 3.3.1 (multiarray error):
```
['',
 '/easybuild/16.04/software/EasyBuild/3.3.1/lib/python2.7/site-packages/vsc_install-0.10.26-py2.7.egg',
BAD -> '/usr/lib/python2.7/dist-packages',
 '/easybuild/16.04/software/EasyBuild/3.3.1/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg',
 '/easybuild/16.04/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_framework-3.3.1-py2.7.egg',
 '/easybuild/16.04/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_easyblocks-3.3.1-py2.7.egg',
 '/easybuild/16.04/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.3.1-py2.7.egg',
 '/easybuild/test/software/HTSeq/0.9.1-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/HTSeq-0.9.1-py2.7-linux-x86_64.egg',
 '/easybuild/test/software/Pysam/0.9.1.4-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg',
 '/easybuild/16.04/software/matplotlib/1.5.3-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/cycler-0.10.0-py2.7.egg',
 '/easybuild/16.04/software/matplotlib/1.5.3-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/matplotlib-1.5.3-py2.7-linux-x86_64.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pyparsing-2.1.5-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pytz-2016.4-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/python_dateutil-2.5.3-py2.7.egg',
 '/easybuild/test/software/Pysam/0.9.1.4-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/Cython-0.25.1-py2.7-linux-x86_64.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/setuptools-23.1.0-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pip-8.1.2-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/blist-1.3.6-py2.7-linux-x86_64.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/Cython-0.24-py2.7-linux-x86_64.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/six-1.10.0-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/python_dateutil-2.5.3-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/decorator-4.0.10-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/liac_arff-2.1.0-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/ecdsa-0.13-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/cryptography-1.4-py2.7-linux-x86_64.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/ipaddress-1.0.17-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/enum34-1.1.6-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pyasn1-0.1.9-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/idna-2.2-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/paramiko-2.0.1-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pyparsing-2.1.5-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/netifaces-0.10.4-py2.7-linux-x86_64.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/funcsigs-1.0.2-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pytz-2016.4-py2.7.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/pandas-0.18.1-py2.7-linux-x86_64.egg',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages/virtualenv-15.0.2-py2.7.egg',
 '/easybuild/16.04/software/EasyBuild/3.3.1/lib/python2.7/site-packages',
 '/easybuild/test/software/HTSeq/0.9.1-foss-2016b-Python-2.7.12/lib/python2.7/site-packages',
 '/easybuild/16.04/software/matplotlib/1.5.3-foss-2016b-Python-2.7.12/lib/python2.7/site-packages',
 '/easybuild/test/software/Pysam/0.9.1.4-foss-2016b-Python-2.7.12/lib/python2.7/site-packages',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python27.zip',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/plat-linux2',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/lib-tk',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/lib-old',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/lib-dynload',
 '/easybuild/16.04/software/Python/2.7.12-foss-2016b/lib/python2.7/site-packages']
```

The content of `$EBROOTPYTHON/lib/python2.7/site-packages/setuptools.pth
./setuptools-23.1.0-py2.7.egg` in both situations is: `./setuptools-23.1.0-py2.7.egg`.

**Comment by boegel** [comment]
@SethosII Do you have a `setuptools.pth` file in the location where EasyBuild is installed @ `$EBROOTEASYBUILD/lib*/python2.7/site-packages/setuptools.pth`?

**Comment by SethosII** [comment]
@boegel There is no `setuptools.pth` in this directory. The contents of the folder are:

```
> ls $EBROOTEASYBUILD/lib*/python2.7/site-packages/
easybuild_easyblocks-3.3.1-py2.7.egg  easybuild_easyconfigs-3.3.1-py2.7.egg  easybuild_framework-3.3.1-py2.7.egg  easy-install.pth  __pycache__  site.py  site.pyc  site.pyo  vsc_base-2.5.8-py2.7.egg  vsc_install-0.10.26-py2.7.egg
```

**Comment by boegel** [comment]
@SethosII What's included in `easy-install.pth`?

**Comment by SethosII** [comment]
@boegel It contains this:

```
> cat $EBROOTEASYBUILD/lib*/python2.7/site-packages/easy-install.pth
import sys; sys.__plen = len(sys.path)
./vsc_install-0.10.26-py2.7.egg
/usr/lib/python2.7/dist-packages
./vsc_base-2.5.8-py2.7.egg
./easybuild_framework-3.3.1-py2.7.egg
./easybuild_easyblocks-3.3.1-py2.7.egg
./easybuild_easyconfigs-3.3.1-py2.7.egg
import sys; new = sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p = getattr(sys, '__egginsert', 0); sys.path[p:p] = new; sys.__egginsert = p + len(new)
```

So the system path is in there.

**Comment by boegel** [comment]
@SethosII Yes, that's the cause for the inclusion of that system location in `sys.path`...

The question remains why it's there. We remove any `setuptools.pth` files in the EasyBuild installation to avoid exactly this (cfr. https://github.com/easybuilders/easybuild-easyblocks/blob/master/easybuild/easyblocks/e/easybuildmeta.py#L104), but apparently it can also happen with `easy-install.pth` (which can't be removed blindly).

Do you mind uploading the installation log for EasyBuild v3.3.1 somewhere for closer inspection (i.e. the `*.log` file in `$EBROOTEASYBUILD/easybuild`)?

Also, can you test whether the problem is fixed by commenting out the `/usr/lib/...` line in that `easy-install.pth`, by prefixing it with a `#`?

**Comment by SethosII** [comment]
Here is the log file: [easybuild-EasyBuild-3.3.1-20170714.131536.log.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/1233606/easybuild-EasyBuild-3.3.1-20170714.131536.log.txt)

The problem is solved by commenting out the system path from `easy-install.pth`.

I also did a `grep` over all `EasyBuild` modules I have and here is the result:

```
> ls /easybuild/16.04/software/EasyBuild
3.0.2  3.1.0  3.1.1  3.1.2  3.2.1  3.3.0  3.3.1
> grep -nr "/usr/lib/python2.7/dist-packages" /easybuild/16.04/software/EasyBuild
/easybuild/16.04/software/EasyBuild/3.1.2/easybuild/easybuild-EasyBuild-3.1.2-20170321.073839.log:325:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.1.2/easybuild/easybuild-EasyBuild-3.1.2-20170321.073839.log:506:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.1.2/easybuild/easybuild-EasyBuild-3.1.2-20170321.073839.log:2037:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.1.2/easybuild/easybuild-EasyBuild-3.1.2-20170321.073839.log:2892:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.1.2/easybuild/easybuild-EasyBuild-3.1.2-20170321.073839.log:13152:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.1.2/easybuild/easybuild-EasyBuild-3.1.2-20170321.073839.log:13347:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.1.2/easybuild/easybuild-EasyBuild-3.1.2-20170321.073839.log:13477:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easy-install.pth:3:/usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.1/easybuild/easybuild-EasyBuild-3.3.1-20170714.131536.log:328:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.1/easybuild/easybuild-EasyBuild-3.3.1-20170714.131536.log:509:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.1/easybuild/easybuild-EasyBuild-3.3.1-20170714.131536.log:2048:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.1/easybuild/easybuild-EasyBuild-3.3.1-20170714.131536.log:2918:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.1/easybuild/easybuild-EasyBuild-3.3.1-20170714.131536.log:13902:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.1/easybuild/easybuild-EasyBuild-3.3.1-20170714.131536.log:14097:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.1/easybuild/easybuild-EasyBuild-3.3.1-20170714.131536.log:14226:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easy-install.pth:3:/usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.0/easybuild/easybuild-EasyBuild-3.3.0-20170628.133207.log:328:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.0/easybuild/easybuild-EasyBuild-3.3.0-20170628.133207.log:509:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.0/easybuild/easybuild-EasyBuild-3.3.0-20170628.133207.log:2048:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.0/easybuild/easybuild-EasyBuild-3.3.0-20170628.133207.log:2921:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.0/easybuild/easybuild-EasyBuild-3.3.0-20170628.133207.log:13821:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.0/easybuild/easybuild-EasyBuild-3.3.0-20170628.133207.log:14016:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.0/easybuild/easybuild-EasyBuild-3.3.0-20170628.133207.log:14145:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.3.0/lib/python2.7/site-packages/easy-install.pth:3:/usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.2.1/easybuild/easybuild-EasyBuild-3.2.1-20170515.094353.log:247:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.2.1/easybuild/easybuild-EasyBuild-3.2.1-20170515.094353.log:416:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.2.1/easybuild/easybuild-EasyBuild-3.2.1-20170515.094353.log:2001:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.2.1/easybuild/easybuild-EasyBuild-3.2.1-20170515.094353.log:2857:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.2.1/easybuild/easybuild-EasyBuild-3.2.1-20170515.094353.log:13494:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.2.1/easybuild/easybuild-EasyBuild-3.2.1-20170515.094353.log:13678:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.2.1/easybuild/easybuild-EasyBuild-3.2.1-20170515.094353.log:13796:Using /usr/lib/python2.7/dist-packages
/easybuild/16.04/software/EasyBuild/3.2.1/lib/python2.7/site-packages/easy-install.pth:3:/usr/lib/python2.7/dist-packages
```

So it's not present in all of them and started in `3.1.2`. Here is also the log file of version `3.1.1` which doesn't has this issue: [easybuild-EasyBuild-3.1.1-20170308.123942.log.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/1233624/easybuild-EasyBuild-3.1.1-20170308.123942.log.txt)

**Comment by SethosII** [comment]
The issue is also present in version `3.4.0`. I also tested an installation on a fresh vm and also got the system path in the `easy-install.pth` file.

**Comment by SethosII** [comment]
I didn't encounter this issue anymore since upgrading to Ubuntu 18.04 (was previously 16.04), so I think we can close this.

Here is a list for reference:

Ubuntu version | EasyBuild version | system path (`/usr/lib/python2.7/dist-packages`) in `lib/python2.7/site-packages/easy-install.pth`
-- | -- | --
14.04 | 3.4.1 | x
16.04 | 3.0.2 |  
16.04 | 3.1.0 |  
16.04 | 3.1.1 |  
16.04 | 3.1.2 | x
16.04 | 3.2.1 | x
16.04 | 3.3.0 | x
16.04 | 3.3.1 | x
16.04 | 3.4.0 | x
16.04 | 3.4.1 | x
16.04 | 3.5.0 | x
16.04 | 3.5.1 | x
16.04 | 3.5.3 | x
16.04 | 3.6.0 | x
16.04 | 3.6.1 | x
16.04 | 3.6.2 | x
16.04 | 3.7.1 | x
16.04 | 3.8.0 | x
18.04 | 3.7.1 |  
18.04 | 3.8.0 |  
18.04 | 3.8.1 |  
18.04 | 3.9.0 |  
18.04 | 3.9.1 |  
18.04 | 3.9.2 |  
18.04 | 3.9.3 |  
18.04 | 3.9.4 |

**Comment by boegel** [comment]
Thanks for following up on this @SethosII!
