### ISSUE TITLE
Building new ParaView-5.4.0-intel-2017b-mpi.eb shows python tracebacks

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-easyconfigs#5280]
When trying to build ParaView 5.4.0 (easyconfig copied from ParaView-5.3.0-foss-2016b-mpi.eb with updates to dependencies matching intel/2017b) i get the following

```
eb ParaView-5.4.0-intel-2017b-mpi.eb --rebuild --debug --buildpath=/pfs/nobackup/home/a/ake/easybuild/builddir --tmpdir=/pfs/nobackup/home/a/ake/easybuild/tmpdir
== temporary log file in case of crash /pfs/nobackup/home/a/ake/easybuild/tmpdir/eb-9rXHH5/easybuild-SatWKR.log
== processing EasyBuild easyconfig /pfs/software/eb/common/custom/easyconfigs/p/ParaView/ParaView-5.4.0-intel-2017b-mpi.eb
== building and installing MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/ParaView/5.4.0-mpi...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
    self.doRollover()
  File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
OSError: [Errno 13] Permission denied
Logged from file run.py, line 478
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 77, in emit
    self.doRollover()
  File "/usr/lib/python2.7/logging/handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
OSError: [Errno 13] Permission denied
Logged from file run.py, line 488
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully
```

Any idea on how to figure out whats goins on?

**Comment by boegel** [comment]
We seen this before, cfr. #1094

**Comment by akesandgren** [comment]
Ok, closing this issue then.
