### ISSUE TITLE
Failure to build numpy/pycrypto

### ISSUE THREAD

**Issue by jpc2350** [easybuilders/easybuild-easyconfigs#5294]
Hi Guys,
Trying to build Python-3.6.3 and Python-3.6.1 with Numpy and Scipy - I get the following error on the Numpy build which causes the test's to fail (and causes the build to fail)
I think this has something to do with Atlas not being available, but I'm not convinced that is the case.
```
Finished processing dependencies for numpy==1.12.1
== 2017-10-04 09:26:36,453 run.py:525 INFO parse_log_for_error msg: Command used: export PYTHONPATH=/tmp/eb-MCURSJ/tmpVF85HL/lib/python2.7/site-packages:$PYTHONPATH && /tools/ebpoc/apps/Python/2.7.13-GCCcore-6.4.0/bin/python setup.py install --prefix=/tmp/eb-MCURSJ/tmpVF85HL
== 2017-10-04 09:26:36,453 run.py:527 INFO parse_log_for_error (some may be harmless) regExp (?<Unable to render embedded object: File ([(,-]) not found.[(,-]|.?\w) found:
_configtest.c:6: error: undefined reference to 'exp'
collect2: error: ld returned 1 exit status
_configtest.c:6: error: undefined reference to 'exp'
collect2: error: ld returned 1 exit status
== 2017-10-04 09:26:36,453 run.py:484 WARNING Found 4 errors in command output (output: _configtest.c:6: error: undefined reference to 'exp', collect2: error: ld returned 1 exit status, _configtest.c:6: error: undefined reference to 'exp', collect2: error: ld returned 1 exit status)
== 2017-10-04 09:26:36,453 run.py:179 INFO running cmd: export PYTHONPATH=/tmp/eb-MCURSJ/tmpVF85HL/lib/python2.7/site-packages:$PYTHONPATH && /tools/ebpoc/apps/Python/2.7.13-GCCcore-6.4.0/bin/python -m timeit -n 3 -r 3 -s "import numpy; x = numpy.random.random((1000, 1000))" "numpy.dot(x, x.T)"
== 2017-10-04 09:26:54,121 build_log.py:157 ERROR EasyBuild crashed with an error (at ?:124 in init): Time for 1000x1000 matrix dot product: 1600 msec >= 500 msec => ERROR (at easybuild/easyblocks/n/numpy.py:269 in test_step)
== 2017-10-04 09:26:54,121 easyblock.py:2650 WARNING build failed (first 300 chars): Time for 1000x1000 matrix dot product: 1600 msec >= 500 msec => ERROR
== 2017-10-04 09:26:54,122 easyblock.py:287 INFO Closing log for application name Python version 2.7.13
```
I've also bumped the version of Numpy to 1.13.3 which returns the same error.

I've tried with LAPACK, OpenBLAS and OpenMPI being added to the builddependencies list, and also without, neither of which works.

Any Ideas?

**Comment by boegel** [comment]
@jpc2350 Which easyconfig are you using here exactly? Is it one included with EasyBuild, or one you created yourself?

It seems like you are trying to build `numpy` with a toolchain that doesn't include a BLAS library, indeed. Just adding `OpenBLAS` to `builddependencies` is not equivalent with using a BLAS-enabled toolchain...

**Comment by jpc2350** [comment]
Hi @boegel,

It's through the python-3.6.1 recipe, so it's using the Numpy easyblock I believe. 

Ahhh, that might be why, I'll look at the toolchain and see if I can get it to work, thanks

**Comment by jpc2350** [comment]
Hi @boegel,

I've built the toolchain for FOSS and GoMPI and the build of NumPY passes - Problem this time comes with the pycrypto extension:

```Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
running build_ext
running build_configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
configure: error: source directory already configured; run "make distclean" there first
Traceback (most recent call last):
  File "setup.py", line 456, in <module>
    core.setup(**kw)
  File "/tools/ebpoc/apps/Python/3.6.1-foss-2017b/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/tools/ebpoc/apps/Python/3.6.1-foss-2017b/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/tools/ebpoc/apps/Python/3.6.1-foss-2017b/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tools/ebpoc/apps/Python/3.6.1-foss-2017b/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/tools/ebpoc/apps/Python/3.6.1-foss-2017b/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/tools/ebpoc/apps/Python/3.6.1-foss-2017b/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 251, in run
    self.run_command(cmd_name)
  File "/tools/ebpoc/apps/Python/3.6.1-foss-2017b/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/tools/ebpoc/apps/Python/3.6.1-foss-2017b/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 278, in run
    raise RuntimeError("autoconf error")
RuntimeError: autoconf error
 (at easybuild/tools/run.py:469 in parse_cmd_output)```

Any Ideas?

**Comment by jpc2350** [comment]
Hi @boegel,

Any idea's on what could be the problem here. It's the standard Python easyconfig recipe file, just installing Python-3.6.3 instead

**Comment by boegel** [comment]
@jpc2350 Sorry for not getting back to this earlier...

Where did you get the sources for `pycrypto`, did EasyBuild auto-download them?

This seems to suggest you somehow grabbed the wrong source tarball?

```
configure: error: source directory already configured; run "make distclean" there first
```

Are we talking about `pycrypto` 2.6.1 here? Is the checksum correct for the source tarball? SHA256 should be `f2ce1e989b272cfcb677616763e0a2e7ec659effa67a88aa92b3a65528f60a3c`.

**Comment by jpc2350** [comment]
Hi @boegel, 
Easybuild auto-downloaded them, 
version 2.6.1 using the latest python-3.6.3.eb recipe from development branch with the SHA256 matching. That's what I initially thought, but checked them, and they're correct.

its a brand new ubuntu 16.04 machine, with the foss-toolchain, AFAIK all the dependencies required for installing python are either installed on the box, or EasyBuild has access to them.

**Comment by jpc2350** [comment]
This is the log from Easybuild in more detail:
```017-11-27 11:09:52,580 filetools.py:1098 INFO Creating directory /tools/build/Python/3.6.3/foss-2017b/pycrypto (parents: True, set_gid: False, sticky: False)
== 2017-11-27 11:09:52,587 run.py:183 INFO running cmd: tar xzf /tools/src/p/Python/extensions/pycrypto-2.6.1.tar.gz
== 2017-11-27 11:09:54,728 run.py:183 INFO running cmd: /tools/apps/Python/3.6.3-foss-2017b/bin/python -V
== 2017-11-27 11:09:54,738 run.py:183 INFO running cmd: /tools/apps/Python/3.6.3-foss-2017b/bin/python -c 'import sys; print(sys.executable)'
== 2017-11-27 11:09:54,800 environment.py:97 INFO Environment variable PYTHONNOUSERSITE set to 1 (previous value: '1')
== 2017-11-27 11:09:54,801 run.py:183 INFO running cmd: /tools/apps/Python/3.6.3-foss-2017b/bin/python -c 'import sys; print(sys.path)'
== 2017-11-27 11:09:54,864 run.py:183 INFO running cmd:  /tools/apps/Python/3.6.3-foss-2017b/bin/python setup.py build
== 2017-11-27 11:10:06,775 build_log.py:158 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd " /tools/apps/Python/3.6.3-foss-2017b/bin/python setup.py build " exited with exitcode 1 and output:
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/Crypto
copying lib/Crypto/pct_warnings.py -> build/lib.linux-x86_64-3.6/Crypto
copying lib/Crypto/__init__.py -> build/lib.linux-x86_64-3.6/Crypto
creating build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/SHA512.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/MD4.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/HMAC.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/SHA384.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/SHA256.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/RIPEMD.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/SHA224.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/MD2.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/SHA.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/MD5.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
copying lib/Crypto/Hash/hashalgo.py -> build/lib.linux-x86_64-3.6/Crypto/Hash
creating build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/AES.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/CAST.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/ARC4.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/DES.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/ARC2.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/XOR.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/DES3.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/Blowfish.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/blockalgo.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.linux-x86_64-3.6/Crypto/Cipher
creating build/lib.linux-x86_64-3.6/Crypto/Util
copying lib/Crypto/Util/Counter.py -> build/lib.linux-x86_64-3.6/Crypto/Util
copying lib/Crypto/Util/randpool.py -> build/lib.linux-x86_64-3.6/Crypto/Util
copying lib/Crypto/Util/winrandom.py -> build/lib.linux-x86_64-3.6/Crypto/Util
copying lib/Crypto/Util/_number_new.py -> build/lib.linux-x86_64-3.6/Crypto/Util
copying lib/Crypto/Util/RFC1751.py -> build/lib.linux-x86_64-3.6/Crypto/Util
copying lib/Crypto/Util/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/Util
copying lib/Crypto/Util/py3compat.py -> build/lib.linux-x86_64-3.6/Crypto/Util
copying lib/Crypto/Util/asn1.py -> build/lib.linux-x86_64-3.6/Crypto/Util
copying lib/Crypto/Util/number.py -> build/lib.linux-x86_64-3.6/Crypto/Util
creating build/lib.linux-x86_64-3.6/Crypto/Random
copying lib/Crypto/Random/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/Random
copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.linux-x86_64-3.6/Crypto/Random
copying lib/Crypto/Random/random.py -> build/lib.linux-x86_64-3.6/Crypto/Random
creating build/lib.linux-x86_64-3.6/Crypto/Random/Fortuna
copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.linux-x86_64-3.6/Crypto/Random/Fortuna
copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.linux-x86_64-3.6/Crypto/Random/Fortuna
copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/Random/Fortuna
copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.linux-x86_64-3.6/Crypto/Random/Fortuna
creating build/lib.linux-x86_64-3.6/Crypto/Random/OSRNG
copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.linux-x86_64-3.6/Crypto/Random/OSRNG
copying lib/Crypto/Random/OSRNG/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/Random/OSRNG
copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.linux-x86_64-3.6/Crypto/Random/OSRNG
copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.linux-x86_64-3.6/Crypto/Random/OSRNG
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest
copying lib/Crypto/SelfTest/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest
copying lib/Crypto/SelfTest/st_common.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Cipher
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Hash
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Protocol
copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Protocol
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/PublicKey
copying lib/Crypto/SelfTest/PublicKey/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/PublicKey
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random
copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random
copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random
copying lib/Crypto/SelfTest/Random/test__UserFriendlyRNG.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random
copying lib/Crypto/SelfTest/Random/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/Fortuna
copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/Fortuna
copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/Fortuna
copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/Fortuna
copying lib/Crypto/SelfTest/Random/Fortuna/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/Fortuna
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/OSRNG
copying lib/Crypto/SelfTest/Random/OSRNG/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Random/OSRNG
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Util
copying lib/Crypto/SelfTest/Util/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Util
creating build/lib.linux-x86_64-3.6/Crypto/SelfTest/Signature
copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Signature
copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Signature
copying lib/Crypto/SelfTest/Signature/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/SelfTest/Signature
creating build/lib.linux-x86_64-3.6/Crypto/Protocol
copying lib/Crypto/Protocol/Chaffing.py -> build/lib.linux-x86_64-3.6/Crypto/Protocol
copying lib/Crypto/Protocol/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/Protocol
copying lib/Crypto/Protocol/KDF.py -> build/lib.linux-x86_64-3.6/Crypto/Protocol
copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.linux-x86_64-3.6/Crypto/Protocol
creating build/lib.linux-x86_64-3.6/Crypto/PublicKey
copying lib/Crypto/PublicKey/_RSA.py -> build/lib.linux-x86_64-3.6/Crypto/PublicKey
copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.linux-x86_64-3.6/Crypto/PublicKey
copying lib/Crypto/PublicKey/_DSA.py -> build/lib.linux-x86_64-3.6/Crypto/PublicKey
copying lib/Crypto/PublicKey/RSA.py -> build/lib.linux-x86_64-3.6/Crypto/PublicKey
copying lib/Crypto/PublicKey/pubkey.py -> build/lib.linux-x86_64-3.6/Crypto/PublicKey
copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.linux-x86_64-3.6/Crypto/PublicKey
copying lib/Crypto/PublicKey/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/PublicKey
copying lib/Crypto/PublicKey/DSA.py -> build/lib.linux-x86_64-3.6/Crypto/PublicKey
creating build/lib.linux-x86_64-3.6/Crypto/Signature
copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.linux-x86_64-3.6/Crypto/Signature
copying lib/Crypto/Signature/__init__.py -> build/lib.linux-x86_64-3.6/Crypto/Signature
copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.linux-x86_64-3.6/Crypto/Signature
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
running build_ext
running build_configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
configure: error: source directory already configured; run "make distclean" there first
Traceback (most recent call last):
  File "setup.py", line 456, in <module>
    core.setup(**kw)
  File "/tools/apps/Python/3.6.3-foss-2017b/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/tools/apps/Python/3.6.3-foss-2017b/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/tools/apps/Python/3.6.3-foss-2017b/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tools/apps/Python/3.6.3-foss-2017b/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/tools/apps/Python/3.6.3-foss-2017b/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/tools/apps/Python/3.6.3-foss-2017b/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 251, in run
    self.run_command(cmd_name)
  File "/tools/apps/Python/3.6.3-foss-2017b/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/tools/apps/Python/3.6.3-foss-2017b/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 278, in run
    raise RuntimeError("autoconf error")
RuntimeError: autoconf error
 (at easybuild/tools/run.py:483 in parse_cmd_output)
== 2017-11-27 11:10:06,776 easyblock.py:2669 WARNING build failed (first 300 chars): cmd " /tools/apps/Python/3.6.3-foss-2017b/bin/python setup.py build " exited with exitcode 1 and output:
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/Crypto
copying lib/Crypto/pct_warnings.py -> build/lib.linux-x86_64-3.6/Crypt
== 2017-11-27 11:10:06,776 easyblock.py:288 INFO Closing log for application name Python version 3.6.3```

**Comment by jpc2350** [comment]
Hi @boegel,

I think I figured the problem.
Using EasyBuild requires me to export PATH=<path/to/modules-3.2.10/>:$PATH which contains `configure`.

Setup.py within the pycrypto folder calls the following command `sh configure`. Which instead of calling the local configure script within the directory, calls the configure script within the modules path.

**Comment by jpc2350** [comment]
Yeah - it's worked. Annoyingly, it could have been avoided if the configure command running through setup.py on pycrypto used the full path or gleaned the full path before running the configure command.

**Comment by fgeorgatos** [comment]
@boegel : could we reopen this one?

I've met this issue today, also, while installing python/3.5.2 using eb/3.5.1; 
met same error, pycrypto, presumably due to same cause.
I suspect a patch file that enforces the correct path would be the right solution here (tbc).

**Comment by boegel** [comment]
@fgeorgatos Up for looking into the required patch to fix this?

Or even better, to report this to upstream so they can fix it?

**Comment by Micket** [comment]
All the versions mentioned here, even after reopening this, are long long since outdated now. Noone was apparently interested in fixing this for these super old python versions, but they are no longer relevant.
