### ISSUE TITLE
Spyder fails because of missing (Py)Qt5 module

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#5600]
I'm running into this issue with `Spyder`:

```
$ spyder3
Traceback (most recent call last):
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/lib/python3.6/site-packages/QtPy-1.3.1-py3.6.egg/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/bin/spyder3", line 3, in <module>
    start.main()
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/lib/python3.6/site-packages/spyder/app/start.py", line 144, in main
    from spyder.app import mainwindow
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/apps/Spyder/3.2.5-intel-2017b-Python-3.6.3/lib/python3.6/site-packages/QtPy-1.3.1-py3.6.egg/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```

(also reported at https://github.com/spyder-ide/qtpy/issues/137)

**Comment by boegel** [comment]
After tracking this down a bit, I think I found the culprit...

After configuring `PyQt5` with `./configure --verbose ...`, the `PyQt5` build log has this:

```
Checking to see if the QtWebKitWidgets module should be built...
...
Project ERROR: Unknown module(s) in QT: webkitwidgets
```

Looking into the `Qt5` log, there's this:

```
Using gcc version ., but at least gcc version 4.7 is required to build Qt WebEngine.
QtWebEngine will not be built.
```

**Comment by boegel** [comment]
The issue with `QtWebEngine` being skipped when installing with the Intel compilers can be fixed with the following patch:

```diff
--- qt-everywhere-opensource-src-5.8.0/qtwebengine/tools/qmake/mkspecs/features/functions.prf.orig	2017-01-03 11:35:11.000000000 +0100
+++ qt-everywhere-opensource-src-5.8.0/qtwebengine/tools/qmake/mkspecs/features/functions.prf	2018-01-04 18:03:39.713451313 +0100
@@ -20,7 +20,7 @@
       skipBuild("Qt WebEngine on Linux requires clang or GCC.")
       return(false)
     }
-    gcc:!clang:!isGCCVersionSupported(): return(false)
+    # gcc:!clang:!isGCCVersionSupported(): return(false)
   } else:win32 {
     winrt {
       skipBuild("WinRT is not supported.")
```

This then leads to another error causing `QtWebEngine` to be skipped:

```
Unmet dependency: dbus
Unmet dependency: libpci
```

Currently trying to rebuild `Qt5` with both `DBus` and `libpci` added as dependencies...
