### ISSUE TITLE
Tkinter requires zlib as dependency

### ISSUE THREAD

**Issue by vanzod** [easybuilders/easybuild-easyconfigs#5788]
Without an underlying `zlib` the build of `Tkinter-3.6.3` fails with the following error:

```
Traceback (most recent call last):
  File "/mnt/ramdisk/Tkinter/3.6.3/foss-2017b-Python-3.6.3/Python-3.6.3/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/mnt/ramdisk/Tkinter/3.6.3/foss-2017b-Python-3.6.3/Python-3.6.3/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/ramdisk/Tkinter/3.6.3/foss-2017b-Python-3.6.3/Python-3.6.3/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/mnt/ramdisk/Tkinter/3.6.3/foss-2017b-Python-3.6.3/Python-3.6.3/Lib/ensurepip/__init__.py", line 189, in _main
    default_pip=args.default_pip,
  File "/mnt/ramdisk/Tkinter/3.6.3/foss-2017b-Python-3.6.3/Python-3.6.3/Lib/ensurepip/__init__.py", line 102, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/mnt/ramdisk/Tkinter/3.6.3/foss-2017b-Python-3.6.3/Python-3.6.3/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
Makefile:1079: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by boegel** [comment]
fixed in #5797, let's follow up there
