### ISSUE TITLE
Paramiko extension in Python 2.7.14 of intel 2017b fails sanity checking

### ISSUE THREAD

**Issue by jhein32** [easybuilders/easybuild-easyconfigs#5916]
I am having issues build Python 2.7.14 for intel 2017b on two installations.  It fails the sanity check of the paramiko extension.    I have no issues building Python-2.7.14-intel-2018.01.eb, Python-2.7.13-intel-2017a.eb and Python-3.6.3-intel-2017b.eb

Below is, what I believe is the relevant section of the debug log:

```
== 2018-02-26 12:55:09,496 extensioneasyblock.py:151 INFO Sanity check for cryptography successful!
== 2018-02-26 12:55:09,497 easyconfig.py:1209 WARNING Unable to resolve template value python -c "import %(ext_name)s" with dict {'nameletterlower': 'p', 'versionsuffix': '', 'toolchain_name': 'intel', 'namelower': 'python', 've\
rsion_minor': '7', 'name': 'Python', 'versionprefix': '', 'version_major': '2', 'nameletter': 'P', 'version_major_minor': '2.7', 'version': '2.7.14', 'toolchain_version': '2017b'}
== 2018-02-26 12:55:09,497 easyconfig.py:1209 WARNING Unable to resolve template value python -c "import %(ext_name)s" with dict {'nameletterlower': 'p', 'versionsuffix': '', 'toolchain_name': 'intel', 'namelower': 'python', 've\
rsion_minor': '7', 'name': 'Python', 'versionprefix': '', 'version_major': '2', 'nameletter': 'P', 'version_major_minor': '2.7', 'version': '2.7.14', 'toolchain_version': '2017b'}
== 2018-02-26 12:55:09,497 extensioneasyblock.py:123 DEBUG starting sanity check for extension with filter ('python -c "import %(ext_name)s"', '')
== 2018-02-26 12:55:09,498 extension.py:153 DEBUG modulename found in self.options, using it: paramiko
== 2018-02-26 12:55:09,498 run.py:163 DEBUG run_cmd: running cmd python -c "import paramiko" (in /home/sw/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14)
== 2018-02-26 12:55:09,498 run.py:183 INFO running cmd: python -c "import paramiko"
== 2018-02-26 12:55:09,678 extension.py:182 WARNING Extension: paramiko failed to install, cmd 'python -c "import paramiko"' (stdin: None) output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/__init__.py", line 31, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 57, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/ed25519key.py", line 22, in <module>
  File "/home/sw/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/site-packages/PyNaCl-1.2.1-py2.7-linux-x86_64.egg/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/home/sw/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/site-packages/PyNaCl-1.2.1-py2.7-linux-x86_64.egg/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/home/sw/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/site-packages/PyNaCl-1.2.1-py2.7-linux-x86_64.egg/nacl/bindings/crypto_box.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: /home/sw/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/site-packages/PyNaCl-1.2.1-py2.7-linux-x86_64.egg/nacl/_sodium.so: undefined symbol: __stack_chk_guard

== 2018-02-26 12:55:09,678 extensioneasyblock.py:146 WARNING Sanity check for paramiko failed: paramiko failed to install, cmd 'python -c "import paramiko"' (stdin: None) output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/__init__.py", line 31, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 57, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/ed25519key.py", line 22, in <module>
  File "/home/sw/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/site-packages/PyNaCl-1.2.1-py2.7-linux-x86_64.egg/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/home/sw/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/site-packages/PyNaCl-1.2.1-py2.7-linux-x86_64.egg/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/home/sw/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/site-packages/PyNaCl-1.2.1-py2.7-linux-x86_64.egg/nacl/bindings/crypto_box.py", line 18, in <module>
```

This is for EB 3.5.1 and we are using CentOS7.   Anyone else is facing this?  Any suggestions on how to solve?

**Comment by boegel** [comment]
This is caused by a bug in the Intel compilers, you can work around this by having `glibc-static` installed, see also #4669 (as already mentioned by @tutufan on the EasyBuild mailing list)
