### ISSUE TITLE
Sphinx with ictce/5.3.0 builds on SL5, but fails on SL6

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#644]
(parent issue: #638)

```
======================================================================
ERROR: Failure: ImportError (cannot import name directives)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/user/scratchdelcatty/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.3-ictce-5.3.0/lib/python2.7/site-packages/nose-1.1.2-py2.7.egg/nose/loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "/user/scratchdelcatty/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.3-ictce-5.3.0/lib/python2.7/site-packages/nose-1.1.2-py2.7.egg/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/user/scratchdelcatty/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Python/2.7.3-ictce-5.3.0/lib/python2.7/site-packages/nose-1.1.2-py2.7.egg/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/vsc40023/easybuild_build/Sphinx/1.1.3/ictce-5.3.0-Python-2.7.3/Sphinx-1.1.3/tests/test_websupport.py", line 21, in <module>
    from sphinx.websupport import WebSupport
  File "../sphinx/websupport/__init__.py", line 21, in <module>
    from sphinx.application import Sphinx
  File "../sphinx/application.py", line 21, in <module>
    from docutils.parsers.rst import convert_directive_function, \
  File "/user/scratchdelcatty/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Docutils/0.9.1-ictce-5.3.0-Python-2.7.3/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 75, in <module>
    from docutils.parsers.rst import states
  File "/user/scratchdelcatty/gent/vsc400/vsc40023/easybuild_REGTEST/SL6/sandybridge/software/Docutils/0.9.1-ictce-5.3.0-Python-2.7.3/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 120, in <module>
    from docutils.parsers.rst import directives, languages, tableparser, roles
ImportError: cannot import name directives

----------------------------------------------------------------------
Ran 26 tests in 1.225s

FAILED (errors=26)
Running Sphinx test suite...
make: *** [test] Error 1
```

**Comment by Micket** [comment]
Long since outdated/resolved
