### ISSUE TITLE
GLib error due to 32bits _collectionsmodule.so

### ISSUE THREAD

**Issue by vwkoppejan** [easybuilders/easybuild-easyconfigs#6622]
GLib-2.53.5-GCCcore-6.4.0.eb keeps crashing with the error below. I'm running eb 3.6.2 on a centos7 box. I've checked and I have a _collectionsmodule.so under /usr/lib64/python2.7/lib-dynload

I reinstalled python using yum just to be sure. Does anyone have tips?

```
make[2]: Entering directory `/data/software/easybuild/build/GLib/2.53.5/GCCcore-6.4.0/glib-2.53.5/glib'
cd .. && \
  /bin/sh ./config.status glib/glibconfig.h
dtrace -C -h -s glib_probes.d -o glib_probes.h.tmp
/bin/sh ../libtool --mode=compile  --tag=CC dtrace -G -s glib_probes.d -o glib_probes.lo
Traceback (most recent call last):
  File "/usr/bin/dtrace", line 25, in <module>
    from shlex import split
  File "/usr/lib/python2.7/shlex.py", line 12, in <module>
    from collections import deque
  File "/usr/lib/python2.7/collections.py", line 8, in <module>
    from _collections import deque, defaultdict
ImportError: /usr/lib/python2.7/lib-dynload/_collectionsmodule.so: wrong ELF class: ELFCLASS32
make[2]: *** [glib_probes.h] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  dtrace -G -s glib_probes.d  -fPIC -DPIC -o .libs/glib_probes.o
Traceback (most recent call last):
  File "/usr/bin/dtrace", line 25, in <module>
    from shlex import split
  File "/usr/lib/python2.7/shlex.py", line 12, in <module>
    from collections import deque
  File "/usr/lib/python2.7/collections.py", line 8, in <module>
    from _collections import deque, defaultdict
ImportError: /usr/lib/python2.7/lib-dynload/_collectionsmodule.so: wrong ELF class: ELFCLASS32
make[2]: *** [glib_probes.lo] Error 1
config.status: executing glib/glibconfig.h commands
config.status: glib/glibconfig.h is unchanged
cd .. && \
  /bin/sh ./config.status glib/glibconfig.h.win32
config.status: creating glib/glibconfig.h.win32
make[2]: Leaving directory `/data/software/easybuild/build/GLib/2.53.5/GCCcore-6.4.0/glib-2.53.5/glib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/software/easybuild/build/GLib/2.53.5/GCCcore-6.4.0/glib-2.53.5'
make: *** [all] Error 2
 (at easybuild/software/EasyBuild/3.6.2/lib/python2.7/site-packages/easybuild_framework-3.6.2-py2.7.egg/easybuild/tools/run.py:501 in parse_cmd_output)
```

**Comment by vwkoppejan** [comment]
I'm able to recreate the error by compiling glib myself. The error shews up when I compile against an Easybuild python module (2.7.14-foss-2017b and 2.7.14-GCCcore-6.4.0-bare). Using my system python the build works.

**Comment by guest1604** [comment]
Hello,

`ImportError: /usr/lib/python2.7/lib-dynload/_collectionsmodule.so: wrong ELF class: ELFCLASS32` 
=> It uses "/usr/lib/python2.7" instead of "/usr/lib64/python2.7".

On CentOS 7, my workaround is to remove "python-libs.i686" package (yum remove python-libs.i686) before installing GLib (and reinstall it after).

**Comment by akesandgren** [comment]
This looks like a problem with dtrace picking up the wrong things. We should probably either make our own dtrace or explicitly turn dtrace support in GLib off if possible.

**Comment by vwkoppejan** [comment]
@guest1604, I'm very, very weary of removing system python libs from my os.
