### ISSUE TITLE
easyconfig tests are suddenly broken

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#6818]
This will make all PR tests run by Travis fail until we get this fixed...

It looks like this may have been caused by the merge of https://github.com/easybuilders/easybuild-framework/pull/2562, but I'm not sure yet (can't seem to spot a problem with it)...

Currently fails with:

```
ERROR: test_dep_versions_per_toolchain_generation (test.easyconfigs.easyconfigs.EasyConfigTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 164, in test_dep_versions_per_toolchain_generation
    self.process_all_easyconfigs()
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 122, in process_all_easyconfigs
    self.ordered_specs = resolve_dependencies(self.parsed_easyconfigs, modules_tool(), retain_all_deps=True)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/easybuild_framework-3.6.3.dev0-py2.6.egg/easybuild/tools/robot.py", line 351, in resolve_dependencies
    raise EasyBuildError("Irresolvable dependencies encountered: %s", ', '.join(irresolvable_mods))
EasyBuildError: 'Irresolvable dependencies encountered: h5py/2.7.0-intel-2017a, MPJ-Express/0.44-goolf-1.4.10'
======================================================================
ERROR: Make sure specified sanity check paths adher to the requirements.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 287, in test_sanity_check_paths
    self.process_all_easyconfigs()
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 122, in process_all_easyconfigs
    self.ordered_specs = resolve_dependencies(self.parsed_easyconfigs, modules_tool(), retain_all_deps=True)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/easybuild_framework-3.6.3.dev0-py2.6.egg/easybuild/tools/robot.py", line 351, in resolve_dependencies
    raise EasyBuildError("Irresolvable dependencies encountered: %s", ', '.join(irresolvable_mods))
EasyBuildError: 'Irresolvable dependencies encountered: h5py/2.7.0-intel-2017a, MPJ-Express/0.44-goolf-1.4.10'
======================================================================
FAIL: Test for parsing of easyconfig Keras-1.0.8-intel-2016b-Python-3.5.2.eb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 1, in innertest
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 519, in template_easyconfig_test
    self.assertEqual(dumped_dep[2], orig_dep[2])
AssertionError: '-HDF5-1.8.17' != '-Python-3.5.2-HDF5-1.8.17'
======================================================================
FAIL: Test for parsing of easyconfig Keras-1.1.0-intel-2016b-Python-3.5.2.eb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 1, in innertest
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 519, in template_easyconfig_test
    self.assertEqual(dumped_dep[2], orig_dep[2])
AssertionError: '-HDF5-1.8.17' != '-Python-3.5.2-HDF5-1.8.17'
======================================================================
FAIL: Test for parsing of easyconfig bat-0.3.3-intel-2017b-Python-3.6.3.eb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 1, in innertest
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 519, in template_easyconfig_test
    self.assertEqual(dumped_dep[2], orig_dep[2])
AssertionError: '-Hadoop-2.6-Java-1.8.0_152' != '-Hadoop-2.6-Java-1.8.0_152-Python-3.6.3'
======================================================================
FAIL: Test for parsing of easyconfig netCDF-4.2.1.1-ictce-5.3.0-zlib-1.2.5.eb
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 1, in innertest
  File "/home/travis/build/easybuilders/easybuild-easyconfigs/test/easyconfigs/easyconfigs.py", line 519, in template_easyconfig_test
    self.assertEqual(dumped_dep[2], orig_dep[2])
AssertionError: '-gpfs' != '-gpfs-zlib-1.2.5'
----------------------------------------------------------------------
Ran 9533 tests in 242.297s
FAILED (failures=4, errors=2)
ERROR: Not all tests were successful.
```

**Comment by boegel** [comment]
Problem should be fixed by https://github.com/easybuilders/easybuild-framework/pull/2566

**Comment by boegel** [comment]
fixed now https://github.com/easybuilders/easybuild-framework/pull/2566 is merged \o/
