### ISSUE TITLE
sympy test failure II

### ISSUE THREAD

**Issue by jose-d** [easybuilders/easybuild-easyconfigs#7425]
as found in #4024 and #7405, sympy tests are _sometimes_ failing.
This issue is to keep the track of the investigation.

So far there is observable correlation between length/depth of the buildpath:

_Long_ path, e.g. `--buildpath=/tmp/fakehome/jose/.local/easybuild/build/` will reproduce the error, and _short_ path, e.g. `--buildpath=/dev/shm/jose/ebtest/` seems to be working fine.

I did just few builds, so this can be also just random noise. - to be confirmed.

test failing seems to be line `4231` of `sympy/printing/pretty/tests/test_pretty.py`:

```
4227 def test_pretty_no_wrap_line():
4228     huge_expr = 0
4229     for i in range(20):
4230         huge_expr += i*sin(i + x)
4231     assert xpretty(huge_expr            ).find('\n') != -1
4232     assert xpretty(huge_expr, wrap_line=False).find('\n') == -1
```

```
________________________________________________________________________________
_____ sympy/printing/pretty/tests/test_pretty.py:test_pretty_no_wrap_line ______
Traceback (most recent call last):
  File "/tmp/fakehome/jose/.local/easybuild/build/sympy/1.3/foss-2018b-Python-3.6.6/sympy-1.3/sympy/printing/pretty/tests/test_pretty.py", line 4231, in test_pretty_no_wrap_line
    assert xpretty(huge_expr            ).find('\n') != -1
AssertionError

 tests finished: 7700 passed, 1 failed, 220 skipped, 351 expected to fail, 
19 expected to fail but passed, in 1953.62 seconds 
DO *NOT* COMMIT!
```

I'm currently digging around..

**Comment by jose-d** [comment]
..tests are looking as not stateless, if `eb` build is interrupted (ctrl-C) in test phase, and then the `eb` command started again and EasyBuild attempts to continue, tests will fail a lot. 

second, most likely unrelated problem is appearing as 
```
 sympy/utilities/_compilation/tests/test_compilation.py:test_compile_link_import_strings 
Traceback (most recent call last):
  File "/home/users/jose/.local/easybuild/build/sympy/1.3/foss-2018b-Python-3.6.6/sympy-1.3/sympy/utilities/_compilation/tests/test_compilation.py", line 61
, in test_compile_link_import_strings
    shutil.rmtree(info['build_dir'])
  File "/sw/local/el7/x86_64/software/lang/Python/3.6.6-foss-2018b/lib/python3.6/shutil.py", line 484, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/sw/local/el7/x86_64/software/lang/Python/3.6.6-foss-2018b/lib/python3.6/shutil.py", line 482, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/users/jose/.local/easybuild/build/sympy/1.3/foss-2018b-Python-3.6.6/sympy-1.3/tmp695y36rc'
```
this seems be similar case to [this bugreport](https://bugs.launchpad.net/nova/+bug/1040110).

**Comment by jose-d** [comment]
> no NFS was involved at all, the build directory was on local disk.

I think that there are some file(s) in the `info['build_dir']` (in my case it's this one:
`/home/users/jose/.local/easybuild/build/sympy/1.3/foss-2018b-Python-3.6.6/sympy-1.3/tmphurt_a5o` )
open in some running process when `shutil.rmtree` is called - in case of NFS it creates the undeletable `.nfsXXX` files, in case of different filesystems it can fail in slightly different way.

> EasyBuild re-creates the build

+1

**Comment by jose-d** [comment]
> ~I think~

now I know. This, 
```
 mod, info = compile_link_import_strings(_sources1, compile_kwargs=compile_kw)
```
will create directory and ELF with compiled sources ( `_sources1` ). [(docu)](https://pycompilation.readthedocs.io/en/latest/pycompilation.html#pycompilation.compilation.compile_link_import_strings)
When the test's are calling
```
shutil.rmtree(info['build_dir']
```
the ELF is still loaded and that's prevents us from clean dir deletion.

Observations on paused buid:

```
[jose@koios1 ceico-easybuilder]$ file /home/users/jose/.local/easybuild/build/sympy/1.3/foss-2018b-Python-3.6.6/sympy-1.3/tmpmigngsiu/.nfs00000000001d87c700000850
/home/users/jose/.local/easybuild/build/sympy/1.3/foss-2018b-Python-3.6.6/sympy-1.3/tmpmigngsiu/.nfs00000000001d87c700000850: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
[jose@koios1 ceico-easybuilder]$
```

**Comment by jose-d** [comment]
>> ..tests are looking as not stateless,
> @jose-d That last problem is strange

no magic too. `CTRL+C` in test phase stops EasyBuild, but test process continues.
Deleted builddir in the next build causes the strange output of the old, still-running test.

From debugging purposes I redirected stdout and stderr of the tests into single file so I was able to see the mix of output of both current and previous test runs.

But they are indeed independent.

**Comment by jose-d** [comment]
sure, I have already workaround and patch. 
Just as the tests-runs are extra long, I do it on the background. 

But I think for 3.8.1 it'll be ready.

**Comment by jose-d** [comment]
ATM i still don't have idea why do we see this. The fact that we see busy files in directories to be deleted has some reason.. I'm playing on the background with this task..

**Comment by jose-d** [comment]
@boegel : i think i have something. can you pls. check this one, https://github.com/easybuilders/easybuild-easyconfigs/pull/7405/commits/2bb40eb9bd26bec296bec506f51f1ec2adeca7e3 (last one in #7405 ) on some of your symlink-home-system?
