### ISSUE TITLE
scikit-image installation fails with "ImportError: No module named '_tifffile'"

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#7491]
Observed with at least `scikit-image-0.14.1-intel-2018b-Python-3.6.6.eb`, reproduced by @vanzod:

```
== 2019-01-24 19:35:09,134 build_log.py:162 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Sanity check failed: extensions sanity check failed for 1 extensions: scikit-image
failing sanity check for 'scikit-image' extension: command "python -c 'import skimage'" failed; output:
/user/gent/400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/external/tifffile/tifffile.py:298: UserWarning: ImportError: No module named '_tifffile'. Loading of some compressed images will be very slow. Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
  "ImportError: No module named '_tifffile'. "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/user/gent/400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/__init__.py", line 177, in <module>
    from .data import data_dir
  File "/user/gent/400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/data/__init__.py", line 18, in <module>
    from ._binary_blobs import binary_blobs
  File "/user/gent/400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/data/_binary_blobs.py", line 2, in <module>
    from ..filters import gaussian
  File "/user/gent/400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/filters/__init__.py", line 3, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File "/user/gent/400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/filters/edges.py", line 17, in <module>
    from ..restoration.uft import laplacian
  File "/user/gent/400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/restoration/__init__.py", line 8, in <module>
    from ._denoise import (denoise_tv_chambolle, denoise_tv_bregman,
  File "/user/gent/400/vsc40023/eb_phanpyscratch/CO7/haswell-ib/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/restoration/_denoise.py", line 6, in <module>
    from ..restoration._denoise_cy import _denoise_bilateral, _denoise_tv_bregman
  File "__init__.pxd", line 872, in init skimage.restoration._denoise_cy
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216,  (at easybuild/framework/easyblock.py:2369 in _sanity_check_step)
```

**Comment by vanzod** [comment]
@boegel I confirm I got the exact same traceback when I built it.

**Comment by vanzod** [comment]
@boegel I also confirm that after switching `'use_pip': False` the build terminates successfully.

**Comment by boegel** [comment]
It looks like the reason it fails when `pip` is used while it works when it's not is related to whether or not a `.egg` directory gets installed:

With a failing installation done with `pip`:
```
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/external/test_tifffile.py
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/external/tifffile
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/external/tifffile/_tifffile.cpython-36m-x86_64-linux-gnu.so
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/external/tifffile/tifffile.py
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/external/tifffile/__pycache__/tifffile.cpython-36.pyc
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/external/__pycache__/test_tifffile.cpython-36.pyc
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/io/tests/test_tifffile.py
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/io/tests/__pycache__/test_tifffile.cpython-36.pyc
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/io/_plugins/tifffile_plugin.py
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/io/_plugins/tifffile_plugin.ini
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/skimage/io/_plugins/__pycache__/tifffile_plugin.cpython-36.pyc
```

With a successful installation with `setup.py install` rather than `pip`:

```
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/external/test_tifffile.py
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/external/tifffile
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/external/tifffile/_tifffile.py
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/external/tifffile/_tifffile.cpython-36m-x86_64-linux-gnu.so
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/external/tifffile/tifffile.py
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/external/tifffile/__pycache__/tifffile.cpython-36.pyc
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/external/tifffile/__pycache__/_tifffile.cpython-36.pyc
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/external/__pycache__/test_tifffile.cpython-36.pyc
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/io/tests/test_tifffile.py
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/io/tests/__pycache__/test_tifffile.cpython-36.pyc
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/io/_plugins/tifffile_plugin.py
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/io/_plugins/tifffile_plugin.ini
/prefix/software/scikit-image/0.14.1-intel-2018b-Python-3.6.6/lib/python3.6/site-packages/scikit_image-0.14.1-py3.6-linux-x86_64.egg/skimage/io/_plugins/__pycache__/tifffile_plugin.cpython-36.pyc
```

**Comment by boegel** [comment]
Or the fact that there's no `skimage/external/tifffile/_tifffile.py` when installing with `pip`. W.T.F.

**Comment by boegel** [comment]
This worked fine when testing #7056 though, where this easyconfig was contributed...

**Comment by boegel** [comment]
Same problem with `scikit-image-0.14.1-foss-2018b-Python-3.6.6.eb`.

Tried re-installing `Python-3.6.6-intel-2018b.eb` from scratch, didn't make a difference.

Also tried with EasyBuild 3.7.1 + `--from-pr 7056`, same issue.

So it seems like the problem is not in the code, but related to one of the dependencies?

**Comment by boegel** [comment]
One more data point: installing `scikit-image-0.14.1-intel-2018b-Python-3.6.6.eb` on top of existing installations of `Python` and the `Pillow`, `dask`, `matplotlib` that were using to correctly install `scikit-image` earlier also fails.

This suggests that it's not a problem with the dependencies, but really when only installing `scikit-image` itself. This is getting really interesting...

**Comment by boegel** [comment]
When taking a detailed look of `pip install --verbose`, I noticed that during the `scikit-image` installation, for some reason it's auto-downloading and installing several Python packages, even though they are already included in the `Python` installation:

```

Installing collected packages: setuptools, wheel, numpy, cython
   Creating /tmp/2176935.master19.golett.gent.vsc/eb-Mk_B4U/pip-build-env-uhpr4zqp/bin
...
Successfully installed cython-0.29.3 numpy-1.16.0 setuptools-40.6.3 wheel-0.32.3
...
Installing build dependencies: finished with status 'done'
Running setup.py (path:/tmp/2176935.master19.golett.gent.vsc/eb-Mk_B4U/pip-req-build-ydexe780/setup.py) egg_info for package from file:///tmp/vsc40023/easybuild_build/scikitimage/0.14.1/intel-2018b-Python-3.6.6/scikitimage/scikit-image-0.14.1
```

That's the likely culprit here, since in the `Python/3.6.6-intel-2018b` we include `numpy` 1.15.0, while now it's pulling in `numpy` 1.16.0, which was released Jan 14th 2019.

So the installation of `scikit-image` 0.14.1 easyconfigs have been broken since that date imho, which explains why this didn't pop up when testing #7056 or during the regression test of EasyBuild v3.8.0...

Question is how to prevent this. We are already using `pip install --no-deps --ignore-installed`, but apparently that's not enough here for some reason...

**Comment by boegel** [comment]
Fixed by making `PythonPackage` use `--no-build-isolation` when using `pip` 10.x or newer, see https://github.com/easybuilders/easybuild-easyblocks/pull/1623
