### ISSUE TITLE
Python-2.7.15-foss-2018b.eb : installation fails at pandas

### ISSUE THREAD

**Issue by cmfield** [easybuilders/easybuild-easyconfigs#7514]
I am trying to easybuild the package in the title, and it fails every time at pandas. For reference, I have managed to install Python/3.7.0-foss-2018b without any difficulty.

```
== 2019-01-29 13:55:14,513 build_log.py:162 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Sanity check failed: extensions sanity check failed for 1 extensions: pandas
failing sanity check for 'pandas' extension: command "python -c "import pandas"" failed; output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nfs/nas22/fs2201/biol_micro_unix_modules/EasyBuild-3.8.0/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/pandas-0.23.1-py2.7-linux-x86_64.egg/pandas/__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: numpy.core.multiarray failed to import not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.,  (at easybuild/framework/easyblock.py:2363 in _sanity_check_step)
== 2019-01-29 13:55:14,513 easyblock.py:2864 WARNING build failed (first 300 chars): Sanity check failed: extensions sanity check failed for 1 extensions: pandas
failing sanity check for 'pandas' extension: command "python -c "import pandas"" failed; output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nfs/nas22/fs2201/biol_micro_unix_modules/Ea
== 2019-01-29 13:55:14,513 easyblock.py:286 INFO Closing log for application name Python version 2.7.15
```

**Comment by cmfield** [comment]
Here you go, I hope it helps:

[debug.log](https://github.com/easybuilders/easybuild-easyconfigs/files/2811617/debug.log)

**Comment by cmfield** [comment]
Good news, I have solved the problem, and it was my fault. I had a python package locally installed that for some truly awful reason referenced the version of python it was installed with in such a way that the path of the wrong version of python ended up in my sys.path, resulting in the loading of the wrong packages. Sorry to trouble you!
