### ISSUE TITLE
failed to install python 2.7.14 for Intel 2017b toolchain

### ISSUE THREAD

**Issue by murfreesboro** [easybuilders/easybuild-easyconfigs#7552]
I tried to install the Python-2.7.14-intel-2017b.eb through "eb --debug --parallel=1 Python-2.7.14-intel-2017b.eb", but it failed on the numpy stage. It reported the error that "can not find the Fortran compiler". Here below is the error message from the log:

```
creating build/src.linux-x86_64-2.7
creating build/src.linux-x86_64-2.7/numpy
creating build/src.linux-x86_64-2.7/numpy/distutils
building library "npymath" sources
Found executable /eb/bin/easybuild/software/Core/icc/2017.4.196-GCC-6.4.0-2.28/compilers_and_libraries_2017.4.196/linux/bin/intel64/icc
Could not locate executable ecc
customize IntelEM64TFCompiler
Found executable /eb/bin/easybuild/software/Core/ifort/2017.4.196-GCC-6.4.0-2.28/compilers_and_libraries_2017.4.196/linux/bin/intel64/ifort
Traceback (most recent call last):
  File "setup.py", line 392, in <module>
    setup_package()
  File "setup.py", line 384, in setup_package
    setup(**metadata)
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/eb/bin/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/eb/bin/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/eb/bin/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/eb/bin/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/eb/bin/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/eb/bin/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/command/build_src.py", line 159, in build_sources
    self.build_library_sources(*libname_info)
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/command/build_src.py", line 294, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/command/build_src.py", line 377, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 672, in get_mathlib_info
    st = config_cmd.try_link('int main(void) { return 0;}')
  File "/eb/bin/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/lib/python2.7/distutils/command/config.py", line 248, in try_link
    self._check_compiler()
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/command/config.py", line 83, in _check_compiler
    self.fcompiler.customize(self.distribution)
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/fcompiler/__init__.py", line 502, in customize
    get_flags('opt', oflags)
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/fcompiler/__init__.py", line 493, in get_flags
    flags.extend(getattr(self.flag_vars, tag))
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/environment.py", line 39, in __getattr__
    return self._get_var(name, conf_desc)
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/environment.py", line 53, in _get_var
    var = self._hook_handler(name, hook)
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/fcompiler/__init__.py", line 703, in _environment_hook
    return hook()
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/fcompiler/intel.py", line 125, in get_flags_opt
    v = self.get_version()
  File "/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1/numpy/distutils/fcompiler/__init__.py", line 434, in get_version
    raise CompilerNotFound()
numpy.distutils.fcompiler.CompilerNotFound
 (at easybuild/EB-develop/easybuild-framework/easybuild/tools/run.py:501 in parse_cmd_output)
== 2019-02-04 15:53:31,958 easyblock.py:2870 WARNING build failed (first 300 chars): cmd " /eb/bin/easybuild/software/MPI/intel/2017.4.196-GCC-6.4.0-2.28/impi/2017.3.196/Python/2.7.14/bin/python setup.py build  --compiler=intel --fcompiler=intelem " exited with exit code 1 and output:
Running from numpy source directory.
```

**Comment by boegel** [comment]
@murfreesboro Can you check in the (`numpy`) build directory if there's a log file somewhere that provides more information?

Should be somewhere in `/tmp/Python/2.7.14/intel-2017b/numpy/numpy-1.13.1` by the looks of it...

Maybe also share the full log somewhere, since we can't tell here what command was being run exactly...

**Comment by murfreesboro** [comment]
@boegel Thank you for your help. Somehow the issue fixed in my box. Maybe I installed something changed the setting to make the error go away. Thank you anyway!

**Comment by murfreesboro** [comment]
error fixed. Close the issue.

**Comment by boegel** [comment]
@murfreesboro Did you update the `numpy` version when you ran into this? Looks like you were hitting this issue: https://github.com/numpy/numpy/pull/12831...
