### ISSUE TITLE
FSL missing some components

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#7899]
The `FSL` easyconfig fails to create components such as `imcp`.

This is the situation in the note described near the top of:

https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation

This is with `5.0.11`.

**Comment by ocaisa** [comment]
Looking at the installation advice at https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/SourceCode

> After building the packages from version 5.0.10 onwards it is necessary to download and build a python environment with the FSL folder in it's final location (it cannot be moved after this). Do this using the provided script:
```$FSLDIR/etc/fslconf/post_install.sh -f $FSLDIR```

I can't see this in the easyblock, so I'm guessing this hasn't been implemented...

**Comment by verdurin** [comment]
Yes, and I'm surprised no-one has noticed this before.
Or perhaps I was unlucky that the first test I ran required some of the missing components.
Is this best raised as an easyblock issue then?

**Comment by ocaisa** [comment]
If you run that script in the installation directory, do things turn out ok? If so then it definitely sounds like an easyblock issue and needs to be fixed there.

**Comment by ocaisa** [comment]
You could always add it as a post-install step but since the easyblock exists, I think it's most appropriate there. To be honest I think it needs further investigation anyway, it says that it will download a python environment which is not something I like the sound of...

**Comment by verdurin** [comment]
Yeah, it's pretty messy. Installs everything using Miniconda.
Owing to local deadlines I installed it manually for now, entirely separately from the EB version.
Happy to help with fixing it properly.
The developers are local (well, twenty minutes' walk away) so perhaps I'll be able to work with them directly.

**Comment by mboisson** [comment]
Can you tell them to ditch conda and use python instead, or at least provide the option to use python instead of conda ? Conda does not work well on clusters.

**Comment by mboisson** [comment]
One of our staff actually tried to add this script to be run at the end of the installation, and it turns into a mess of Conda trying to write stuff in the installer's account.

**Comment by leorojas82** [comment]
I also noticed eb does not run the post-installation step from FSL documentation, so fslpython does not get built at the end.  As already mentioned,  fslpython is a  conda env, so it contains  pre-compiled binaries.  I ran the fslpython build manually, and then attempted to run the test suit provided by Oxford FMRIB (the so called FEEDS), but it failed, since the pre-compiled binaries required HDF5 1.10.1, where as eb installs HDF5 1.10.2 as a dependency of FSL. So at the end I had to build HDF5 1.10.1 and build FSL against it, run the post-installation by hand, All worked fine at the end. I don't know if the easyblock could do all that for us, also running FEEDS at the end will be great as a testing mechanism.

**Comment by casparvl** [comment]
Any update on this? Anyone has a working solution for now?

I bumped into the same issue. I got FEEDS to run in the end by pulling in the missing I/O scripts from an old source (5.0.10, from before they were moved to the Python-part of the installation). However, I'm not sure what else I might be missing...

@verdurin It might be a really great idea if you talk to them and make them aware of our perspective of things (i.e. as people managing larger systems with many software installations). I think it could really be in their benifit (more users / impact of their software) if they understand our challenges with a) installations that locally pull in a Miniconda and b) custom installations that have both a configure-make and python part.

**Comment by verdurin** [comment]
@casparvl I have re-started the discussion with them, and now have a (long...) list of packages required for `fsl_python`. So far I've lacked the time to do anything with this. The willingness on their part to help is there.

**Comment by casparvl** [comment]
@verdurin Ok, great to hear they are willing at least.

Do you have any way you got this working for now? If I just added

```
$FSLDIR/etc/fslconf/post_install.sh -f $FSLDIR
```
As a postinstallcmd (as suggested according to https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/SourceCode). But: 

```
== 2019-10-22 20:44:25,197 run.py:589 INFO parse_log_for_error (some may be harmless) regExp (?<![(,-]|\w)(?:error|segmentation fault|failed)(
?![(,-]|\.?\w) found:
Failed to create FSL Python environment - see /scratch-shared/casparl/eb-Gm_lUn/fslpythonZH0D/fslpython_miniconda_installer.log for details
Post install setup failed
```
Unfortunately, that tmpdir was already removed before I could check those logs =) But I'm guessing it is the problem @leorojas82 mentioned earlier, of the binaries shipped as part of fslpython are linked to HDF5-1.10.1.

Is there any acceptable workaround for now? Did anyone create an EasyConfig that works (even if it should really be fixed as part of the block in the long run)? Or did you all just do the postinstallstep manually?

**Comment by akesandgren** [comment]
--disable-cleanup-tmpdir --disable-cleanup-builddir ??

**Comment by tardigradus** [comment]
Does anyone know whether the EC for version 6.0.3 still has this problem?

**Comment by verdurin** [comment]
@tardigradus Don't believe it's been fixed yet, no, and I haven't had time yet to look into this with Oxford colleagues.

**Comment by znee** [comment]
Hi guys, I got the same problem. fslpython, as well as miniconda environment are not installed. Any solutions?

**Comment by pcamach2** [comment]
@znee I'm getting the same issue with 6.0.3 installation (/usr/local/fsl/etc/fslconf/fslpython_install.sh lines 188-191 can't find /usr/local/fsl/fslpython/bin/conda)

**Comment by znee** [comment]
Hi guys, I posted this problem and I got a following answer.

https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=FSL;bd0fa8bf.2004

This worked for me, and I hope I would work for you.

**Comment by tardigradus** [comment]
@znee  Have you integrated this into the easyconfig?

**Comment by verdurin** [comment]
Various of us think the better long-term approach within EB is to specify the `fslpython` environment and its tools directly, not using anything `Conda`-related. I know at least one person is planning to look at this soon and I will assist where I can. The idea of integrating the above into the `easyconfig` is not appealing... (though it's certainly helpful to share workaround).

**Comment by dak13204** [comment]
@znee how did you change line 149 in the fslpython_install.sh? The file is locked for me and I cannot change the code in line 149 like you were instructed. I'm pretty new to coding and all this so any help would be very much appreciated

**Comment by pcamach2** [comment]
@dak13204 is the fslpython_install.sh read-only for your user account on your machine? If you can change the file ownership, do so while you're editing it and then change it back if you want to avoid accidental changes. If you can't change file ownership, but you can remove files in the install directory, you can always make a copy of the script in a folder you have privileges for and change that file as necessary, which then can replace the original file. Otherwise, I'd suggest installing FSL to a folder for which you have privileges and can make the necessary changes, especially if you're the only user that needs this FSL install.

**Comment by dak13204** [comment]
@pcamach2 thank you! When I installed FSL the first time, I just followed a video tutorial that downloaded it to /usr/local/fsl which I guess is why I was unable to edit the fslpython_install.sh file. I didn't realize I could install FSL wherever I wanted. I just reinstalled FSL to a folder that I have privileges to and was able to successfully edit the fslpython_install.sh file. So now I need to uninstall FSL from the first time I installed it but I am not sure how to do that since I don't have privileges. Do you have any idea how I can uninstall the program from the first time I installed it?

**Comment by pcamach2** [comment]
@dak13204 no problem! I've never been in a scenario where I had to remove FSL without privileges, so I'm not sure what your best bet is there. If you can't run rm -R on /usr/local/fsl, you should contact whoever has privileges to do so.

Into the meantime, you can always ensure that your path variable only includes your new FSL install location so that you know which copy is running. If you use the bash terminal, this would be done by editing ~/.bashrc or ~/.bash_profile depending on what operating system you're using. Make sure to comment out or delete any export statements for PATH to /usr/local/fsl/bin and insert: export PATH=$PATH:/path/to/new_fsl/bin

**Comment by rinivarg** [comment]
> Hi guys, I posted this problem to FSL mail list, and I got a following answer.
> 
> https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=FSL;bd0fa8bf.2004
> 
> This worked for me, and I hope I would work for you.

**Comment by bedroge** [comment]
We just ran into the same issue:
```
/software/software/FSL/6.0.3-foss-2019b-Python-3.7.4/fsl/bin/bedpostx_preproc.sh: line 71: /software/software/FSL/6.0.3-foss-2019b-Python-3.7.4/fsl/bin/imcp: No such file or directory
/software/software/FSL/6.0.3-foss-2019b-Python-3.7.4/fsl/bin/tbss_2_reg: line 130: /software/software/FSL/6.0.3-foss-2019b-Python-3.7.4/fsl/bin/imglob: No such file or directory
```

Is there any progress on including a solution in the easyblock/easyconfig? Or is there an easy, temporary workaround for this? I tried loading the module and running `FSLDIR/etc/fslconf/fslpython_install.sh -f $FSLDIR`, but that fails with the following error:
```
PREFIX=/home/f115261/easybuildinstall/software/FSL/6.0.3-foss-2019b-Python-3.7.4/fsl/fslpython
Unpacking payload ...
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 368, in _queue_management_worker
  File "multiprocessing/connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 611, in result_iterator
  File "concurrent/futures/_base.py", line 439, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[5092] Failed to execute script entry_point
```

**Comment by bedroge** [comment]
Turned out the latter was caused by exceeding my quota on the number of files... So it does seem to work now, but it would still be nice to have a better solution than this Conda environment with a huge pile of stuff in it.

**Comment by casparvl** [comment]
@bedroge If you based yourself on the EasyConfigs for foss-2019a, the following section was probably commented out:

```
#
# Adding the bin from the virtualenv was the only way to get things working...
#
# NOTE: This did after extensiv tests not apply to the 2019a toolchain, please see
# https://github.com/easybuilders/easybuild-easyconfigs/issues/9654
#
# modextrapaths = {
#     'PATH': 'fsl/fslpython/bin',
#     'PYTHONPATH': 'fsl/fslpython/envs/fslpython/lib/python3.7/site-packages/',
# }
```
I was the one who added that stuff in the `foss-2018b` based EasyConfigs for FSL, since it was the only way I ever got things to work. In `foss-2019a` they were taken out because for @crubb it worked also without this. If for you, it again doesn't work, there must be a dependency on something related to the system (Could be something like: if the system provides a python 3.X maybe it works out of the box, otherwise not. Or could have to do with your installation path, I had problems with the hardcoded shebang that got inserted in the some of FSLs python files).

Anyway, if you want it solved within easybuild, you can give a try to uncommenting those and see if that helps. In any case, it is an ugly installation...

**Comment by Zahra925** [comment]
Hello,

I receive this error during FSL installation through Ubuntu shell via
python /mnt/c/Users/<WindowsUserName>/Downloads/fslinstaller.py

Stage 1
By installing this python distribution you agree to the license terms in
/usr/local/fsl/fslpython/LICENSE.txt
100%
Stage 2
100%
----- ERROR -----
Failed to create FSL Python environment - see /tmp/fslpythonEXRz/fslpython_miniconda_installer.log for details
Post install setup failed.

your help/comment greatly appreciated.

Thanks,
Zahra

**Comment by pcamach2** [comment]
@Zahra925 Can you provide more details from the log file?

**Comment by wouterbosmans** [comment]
Hi, Got the same problem. This is what I find in the log file:

Installing FSL conda distribution into /usr/local/fsl/fslpython
--2021-02-16 09:08:29--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8303, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.

Thank you for helping,
Wouter

**Comment by cmeesters** [comment]
Hi,

Using eb it is impossible to install FSL v6.0.4, see my [post on the FSL mailinglist](https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2103&L=FSL&O=D&P=115545). Basically, every new version apparently needs new patches. This is particularly hard to work out at times, because the distribution ships libraries sometimes even in two copies, which are incompatible. Even, if this is sorted out, there are undefined references and the FSL maintainers do not name all dependencies. Some necessary patches indicate, that one unknown machine satisfies all dependencies ('home' in include paths).

FSL maintainers need to fix their software. I was unable to download a container - even though this was indicated as an option. But was pointed to  https://github.com/ReproNim/neurodocker . Perhaps this a solution for some.

Cheers
Christian

**Comment by verdurin** [comment]
@cmeesters thanks for taking a look, at least. I have used **neurodocker** a bit, and it's not problem-free either, unfortunately.

**Comment by verdurin** [comment]
Worth also mentioning that there has been some work in the EB community on translating the Conda aspect into explicit Python dependencies, but that relied on local variations from upstream. Does at least show that it appears possible.

**Comment by cmeesters** [comment]
@verdurin I did not try neurodocker, so far. Regardless, I will try to keep on that FSL issue.

 Does anyone know how to contact FSL developers, directly (without that mailinglist, where some requests are likely to be ignored)?

**Comment by tardigradus** [comment]
This page for the group which develops FSL seems to be [here](https://www.win.ox.ac.uk/research/analysis-research/analysis-people).  Steven Smith seems to be the head honcho, but there are some IT people listed there who probably do the actual coding.

Regarding neurodocker, I am sure the developers have worthy aims, but I see more and more people, particularly in the fields of neuroscience and bioinformatics, trying to get old, shaky software to fly.  In such situations, some seem to see containerisation  as better solution than actually fixing and/or updating the software itself.  However, I worry that all the time we save through using EasyBuild will be eaten up by trying to repair broken containers that users dump on our HPC doorsteps.  Then again I don't have much experience with Docker and co. so maybe I'm being overly pessimistic.

Regarding FSL itself, the software seems to have gone slightly out of fashion with our users, so personally I currently have no pressing need to see it in EasyBuild.

**Comment by cmeesters** [comment]
@tardigradus  Thank you, I just wrote that mail (the top page does not really indicate who is in charge nor does the Smith group page). Be that as it may, its worth a shot.

BTW: I agree with your estimation of the situation and your fears. All of them.

**Comment by cmeesters** [comment]
`FSL is not quite out-of-fasion` 
which is why I pursuing this, point granted ;-)

**Comment by mboisson** [comment]
If you are interested, this is the commit that we used in Compute Canada. It includes patches and the requirements.txt file to create a virtual environment (insteadof Conda)

https://github.com/ComputeCanada/easybuild-easyconfigs/commit/7b05bcb193f54b66d364c85355f0ea2595de8672

**Comment by mboisson** [comment]
Yes, I have WIP for FSL 6.0.4, with the modified `mist-clean`. The issue there is that one of the python packages does not have a public release outside of conda for the version that is being used in 6.0.4. 
https://github.com/mabast85/eddy_qc_release/issues/1

I can commit the modified patches, but it won't be possible to install the same versions as those used by FSL 6.0.4 unless they release that new version of `eddy_qc`.

**Comment by cmeesters** [comment]
Meanwhile I got provided with a singularity container. Works fine.

The idea among the FSL is to go ahead and distribute the individual FSL applications as individual Conda packages. My only hope is, that the source code becomes open and that some, based on the conda recipes contribute cmake list files or similar, such that conda-less eb or spack integration is straightforward.

**Comment by verdurin** [comment]
@mboisson looks like there is a `1.0.3` release for `eddy_qc` now:
https://github.com/mabast85/eddy_qc_release/commit/7f10fbc396472370d6eef61717d9bfa071050b97
at least in terms of commits.
