### ISSUE TITLE
gensim extension in Annif easyconfig fails to install with intel/2019a toolchain

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#8540]
The `import gensim` check fails with:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/software/Annif/0.40.0-intel-2019a-Python-3.7.2/lib/python3.7/site-packages/gensim/__init__.py", line 5, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401
  File "/software/Annif/0.40.0-intel-2019a-Python-3.7.2/lib/python3.7/site-packages/gensim/models/__init__.py", line 15, in <module>
    from .doc2vec import Doc2Vec  # noqa:F401
  File "/software/Annif/0.40.0-intel-2019a-Python-3.7.2/lib/python3.7/site-packages/gensim/models/doc2vec.py", line 357, in <module>
    from gensim.models.doc2vec_corpusfile import (
  File "gensim/models/word2vec_corpusfile.pxd", line 33, in init gensim.models.doc2vec_corpusfile
  File "gensim/models/word2vec_corpusfile.pyx", line 40, in init gensim.models.word2vec_corpusfile
AttributeError: type object 'gensim.models.word2vec_corpusfile.CythonVocab' has no attribute '__reduce_cython__'
```

Based on https://github.com/cython/cython/issues/1953, I tried rebuilding the Cython part of `gensim` (although what C source files included in the source tarball indicate that they were generated using Cython 0.29.2, which is recent enough) by using:

```python
exts_list = [
    ...
    ('gensim', '' {
        ...
        'preinstallopts': "python setup.py build_ext --inplace && ",
    ),
    ...
```

The `build_ext` part fails because it tries to use `gcc` when linking:

```
gcc -shared ... -O2 -xHost -ftz -fp-speculation=safe -fp-model source ... -o build/lib.linux-x86_64-3.7/gensim/models/word2vec_inner.cpython-37m-x86_64-linux-gnu.so
gcc: error: source: No such file or directory
gcc: error: unrecognized command line option ‘-ftz’; did you mean ‘-flto’?
gcc: error: unrecognized command line option ‘-fp-speculation=safe’
gcc: error: unrecognized command line option ‘-fp-model’
command 'gcc' failed with exit status 1
```

(this goes undetected, no non-zero exit code, so `eb` proceeds and the `import gensim` fails as before)

I haven't found a way to make Cython use `icc` rather than `gcc` as the linker command (it already uses `icc` for compiling though, based on `$CC` being set to `icc`).

**Comment by boegel** [comment]
Turns out the magic incantation is to set `$LDSHARED` to `"icc -shared"` to convince `python setup.py build_ext --inplace` to use `icc -shared` as linker command, so this works as expected:

```python
    ('gensim', '3.7.3', {
        'checksums': ['621fe72ee1bb0e16008c34f9f5ca6168bbfc82fc85907f7254974776e482e156'],
        'preinstallopts': 'LDSHARED="icc -shared" python setup.py build_ext --inplace && ',
    }),
```

Hat tip to @Darkless012 for figuring this one out! :)

Closing this, will add the resulting easyconfig to #8536...
