### ISSUE TITLE
TensorFlow-1.14.0-fosscuda-2019a-Python-3.7.2 not finding libcuda.so.1

### ISSUE THREAD

**Issue by terjekv** [easybuilders/easybuild-easyconfigs#9183]
After building TensorFlow-1.14.0-fosscuda-2019a-Python-3.7.2 the build completes successfully and one can load tensorflow. However, tensorflow fails to find libcuda.so.1:

```
Python 3.7.2 (default, Oct 20 2019, 14:14:01)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2019-10-20 19:49:52.912562: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
--------------------------------------------------------------------------
The library attempted to open the following supporting CUDA libraries,
but each of them failed.  CUDA-aware support is disabled.
libcuda.so.1: cannot open shared object file: No such file or directory
libcuda.dylib: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.so.1: cannot open shared object file: No such file or directory
/usr/lib64/libcuda.dylib: cannot open shared object file: No such file or directory
If you are not interested in CUDA-aware support, then run with
--mca mpi_cuda_support 0 to suppress this message.  If you are interested
in CUDA-aware support, then try setting LD_LIBRARY_PATH to the location
of libcuda.so.1 to get passed this issue.
--------------------------------------------------------------------------
```

In the generated module for CUDA/10.1.105-GCC-8.2.0-2.31.1.lua, we find: 

prepend_path("LIBRARY_PATH", pathJoin(root, "lib64"))
prepend_path("LIBRARY_PATH", pathJoin(root, "lib64/stubs"))

Adding these same paths to LD_LIBRARY_PATH resolves the problem. I am unfortunately uncertain how the module file is generated so I resorted to fixing this manually in the Lua file.

**Comment by boegel** [comment]
@terjekv This may be because of a missing patch. Which patch files did you include in the `TensorFlow` easyconfig (related to CUDA)?

**Comment by terjekv** [comment]
@boegel Er, I didn't apply any manual patches. I installed Tensorflow via `eb TensorFlow-1.14.0-fosscuda-2019a-Python-3.7.2.eb` out of the box, as it came from EasyBuild 4.0.1. Should I not have?

**Comment by boegel** [comment]
@terjekv Sorry, I overlooked that we already include that exact easyconfig.

There should be no need for changing it, it should work...

The fix you applied to the `CUDA` module file can be easily reproduced in the easyblock we use to install `CUDA`, but the question is why you need it, while it hasn't been an issue for others...

Any idea here @akesandgren, @wpoely86?

**Comment by akesandgren** [comment]
You're missing the cuda driver OS package, in Ubuntu/Debian that would be libcuda1-xxx where xxx is the nvidia driver  version.
libuda.so.1 doesn't come from EasyBuild, but from the nvidia driver OS package.

Don't know what it's called in RH/CentOS based distros.

The library in stubs is just that, a stub, it doesn't contain any actual code, just dummy function entries so you can link things against it without having to have the driver library installed. But when running you do need the actual driver lib.

**Comment by terjekv** [comment]
Aha! I am indeed missing the CUDA driver OS package. I didn't think of them as I was getting things built. Thank you!

**Comment by boegel** [comment]
@akesandgren Can we somehow clearly report this, either through an OS dep or via an extra check in the TensorFlow easyblock?

**Comment by akesandgren** [comment]
Not really, this is a pure runtime dep that we don't really want in either the easyconfig or block. And you need it for everything using CUDA anyway... could perhaps add a comment or so in the CUDA easyconfigs but...

**Comment by terjekv** [comment]
Right. To resolve this on RHEL8:

```
# dnf config-manager --add-repo http://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
# dnf clean all
# dnf -y install cuda-drivers
# modprobe nvidia
```

And then things worked. However, I had to retain `prepend_path("LD_LIBRARY_PATH", pathJoin(root, "lib64"))` in the module file (but I did remove the stubs directory). The machine does not have CUDA installed outside of EasyBuild, it just has the driver.

**Comment by boegel** [comment]
@terjekv Which errors are you getting without having `lib64` added to `$LD_LIBRARY_PATH`?

**Comment by terjekv** [comment]
```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/opt/uio/modules/rhel8/easybuild/software/TensorFlow/1.14.0-fosscuda-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.
py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/uio/modules/rhel8/easybuild/software/TensorFlow/1.14.0-fosscuda-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_
internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/uio/modules/rhel8/easybuild/software/TensorFlow/1.14.0-fosscuda-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_
internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/uio/modules/rhel8/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/uio/modules/rhel8/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/uio/modules/rhel8/easybuild/software/TensorFlow/1.14.0-fosscuda-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow/__init__.py", line 28, in
 <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/opt/uio/modules/rhel8/easybuild/software/TensorFlow/1.14.0-fosscuda-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow/python/__init__.py", line
 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/opt/uio/modules/rhel8/easybuild/software/TensorFlow/1.14.0-fosscuda-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.
py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/opt/uio/modules/rhel8/easybuild/software/TensorFlow/1.14.0-fosscuda-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.
py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/opt/uio/modules/rhel8/easybuild/software/TensorFlow/1.14.0-fosscuda-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_
internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/opt/uio/modules/rhel8/easybuild/software/TensorFlow/1.14.0-fosscuda-2019a-Python-3.7.2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_
internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/uio/modules/rhel8/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/uio/modules/rhel8/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by boegel** [comment]
@terjekv It looks like you've accidentally removed the update statement for the `$LD_LIBRARY_PATH` for the path to the `lib64` subdir from the module file.

It should be there in a `CUDA` module generated by EasyBuild, if you haven't touched it...

**Comment by terjekv** [comment]
Sounds good, let's assume I did something stupid. If this is an ongoing issue, it'll crop up again.
