### ISSUE TITLE
GC3Pie-2.5.2.eb - Error while compiling

### ISSUE THREAD

**Issue by nortex** [easybuilders/easybuild-easyconfigs#9210]
Hi, i am trying to compile GC3Pie-2.5.2.eb with the standard command:

`eb GC3Pie-2.5.2.eb -r`

EB version:  3.9.4
OS: CentOS 6.7

During the extensions installation i get the next error: 

```
== 2019-10-27 14:02:01,748 run.py:192 INFO running cmd: unzip -qq /data/sources/g/GC3Pie/extensions/setuptools-41.0.1.zip
== 2019-10-27 14:02:02,396 run.py:192 INFO running cmd: /usr/bin/python -V
== 2019-10-27 14:02:02,430 run.py:192 INFO running cmd: /usr/bin/python -c 'import sys; print(sys.executable)'
== 2019-10-27 14:02:02,484 environment.py:97 INFO Environment variable PYTHONNOUSERSITE set to 1 (previously undefined)
== 2019-10-27 14:02:02,485 run.py:192 INFO running cmd: /usr/bin/python -c 'import sys; print(sys.path)'
== 2019-10-27 14:02:02,539 run.py:192 INFO running cmd:  /usr/bin/python setup.py build
== 2019-10-27 14:02:03,189 build_log.py:163 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd " /usr/bin/python setup.py build " exited with exit code 1 and output:
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/setuptools/__init__.py", line 18, in <module>
    import setuptools.version
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/pkg_resources/__init__.py", line 959, in <module>
    class Environment:
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/pkg_resources/__init__.py", line 963, in Environment
    self, search_path=None, platform=get_supported_platform(),
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/pkg_resources/__init__.py", line 190, in get_supported_platform
    plat = get_build_platform()
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/pkg_resources/__init__.py", line 393, in get_build_platform
    from sysconfig import get_platform
ImportError: No module named sysconfig
 (at easybuild/tools/run.py:501 in parse_cmd_output)
== 2019-10-27 14:02:03,189 easyblock.py:3053 WARNING build failed (first 300 chars): cmd " /usr/bin/python setup.py build " exited with exit code 1 and output:
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/setuptools/__init__.py", line 18, in <module>
```
Any ideas what is the problem?

**Comment by ocaisa** [comment]
> Now i have the next error (trying to install the 2.5.0 version to avoid checksum errors):

You can safely remove the checksums in the edited easyconfig. 

The error you show is a problem untarring something, that's a very strange one, is that a restriction on the filesystem?

If I was you, I would go back to an edited 2.5.2 version:
```
easyblock = 'PythonBundle'

name = 'GC3Pie'
version = '2.5.3'

homepage = 'https://gc3pie.readthedocs.org'
description = """GC3Pie is a Python package for running large job campaigns on diverse batch-oriented execution
 environments."""

toolchain = SYSTEM

osdependencies = [('python-devel', 'python-dev')]

# allow use of system Python
allow_system_deps = [('Python', SYS_PYTHON_VERSION)]

builddependencies = [('pkg-config', '0.29.2')]
dependencies = [
    ('PyYAML', '3.13'),
    ('libffi', '3.2.1'),  # required dep for PyNaCl
]

use_pip = False

exts_default_options = {
    'source_urls': [PYPI_SOURCE],
}

exts_list = [
    ('setuptools', '36.8.0', {
        'source_tmpl': 'setuptools-%(version)s.zip',
    }),
    ('pyCLI', '2.0.3', {
        'modulename': 'cli',
        'checksums': ['bc53e6c5db031ae1c05d131641f153d22a201c5e82cc8c9324a945752efbb622'],
    }),
    ('prettytable', '0.7.2', {
        'checksums': ['2d5460dc9db74a32bcc8f9f67de68b2c4f4d2f01fa3bd518764c69156d9cacd9'],
    }),
    ('dictproxyhack', '1.1', {
        'checksums': ['964eef82fba883d53783b08cbce90415380a5c26e5c2dba47548d1c3d0a591f8'],
    }),
    ('monotonic', '1.5', {
        'checksums': ['23953d55076df038541e648a53676fb24980f7a1be290cdda21300b3bc21dfb0'],
    }),
    ('humanfriendly', '4.18', {
        'checksums': ['33ee8ceb63f1db61cce8b5c800c531e1a61023ac5488ccde2ba574a85be00a85'],
    }),
    ('coloredlogs', '10.0', {
        'checksums': ['b869a2dda3fa88154b9dd850e27828d8755bfab5a838a1c97fbc850c6e377c36'],
    }),
    ('blinker', '1.4', {
        'checksums': ['471aee25f3992bd325afa3772f1063dbdbbca947a041b8b89466dc00d606f8b6'],
    }),
    ('SQLAlchemy', '1.3.5', {
        'checksums': ['c30925d60af95443458ebd7525daf791f55762b106049ae71e18f8dd58084c2f'],
    }),
    ('lockfile', '0.12.2', {
        'checksums': ['6aed02de03cba24efabcd600b30540140634fc06cfa603822d508d5361e9f799'],
    }),
    ('docutils', '0.15.2'),
    ('python-daemon', '2.2.3', {
        'modulename': 'daemon',
        'checksums': ['affeca9e5adfce2666a63890af9d6aff79f670f7511899edaddca7f96593cc25'],
    }),
    ('future', '0.17.1', {
        'checksums': ['67045236dcfd6816dc439556d009594abf643e5eb48992e36beac09c2ca659b8'],
    }),
    ('parsedatetime', '2.4', {
        'checksums': ['3d817c58fb9570d1eec1dd46fa9448cd644eeed4fb612684b02dfda3a79cb84b'],
    }),
    ('pycparser', '2.19', {
        'checksums': ['a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3'],
    }),
    ('six', '1.12.0', {
        'checksums': ['d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73'],
    }),
    ('PyNaCl', '1.3.0', {
        'modulename': 'nacl',
        'checksums': ['0c6100edd16fefd1557da078c7a31e7b7d7a52ce39fdca2bec29d4f7b6e7600c'],
    }),
    ('bcrypt', '3.1.7', {
        'checksums': ['0b0069c752ec14172c5f78208f1863d7ad6755a6fae6fe76ec2c80d13be41e42'],
    }),
    ('ipaddress', '1.0.22', {
        'checksums': ['b146c751ea45cad6188dd6cf2d9b757f6f4f8d6ffb96a023e6f2e26eea02a72c'],
    }),
    ('asn1crypto', '0.24.0', {
        'checksums': ['9d5c20441baf0cb60a4ac34cc447c6c189024b6b4c6cd7877034f4965c464e49'],
    }),
    ('idna', '2.8', {
        'checksums': ['c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407'],
    }),
    ('enum34', '1.1.6', {
        'modulename': 'enum',
        'checksums': ['8ad8c4783bf61ded74527bffb48ed9b54166685e4230386a9ed9b1279e2df5b1'],
    }),
    ('cryptography', '2.7', {
        'checksums': ['e6347742ac8f35ded4a46ff835c60e68c22a536a8ae5c4422966d06946b6d4c6'],
    }),
    ('pyasn1', '0.4.5', {
        'checksums': ['da2420fe13a9452d8ae97a0e478adde1dee153b11ba832a95b223a2ba01c10f7'],
    }),
    ('paramiko', '2.6.0', {
        'checksums': ['f4b2edfa0d226b70bd4ca31ea7e389325990283da23465d572ed1f70a7583041'],
    }),
    ('pycrypto', '2.6.1', {
        'modulename': 'Crypto',
        'checksums': ['f2ce1e989b272cfcb677616763e0a2e7ec659effa67a88aa92b3a65528f60a3c'],
    }),
    ('cffi', '1.12.3', {
        'checksums': ['041c81822e9f84b1d9c401182e174996f0bae9991f33725d059b771744290774'],
    }),
    ('gc3pie', version, {
        'modulename': 'gc3libs',
    }),
]

local_pyshortver = '.'.join(SYS_PYTHON_VERSION.split('.')[:2])

# on RHEL-based systems, some extensions get installed to lib, some to lib64
modextrapaths = {
    'PYTHONPATH': ['lib/python%s/site-packages' % local_pyshortver, 'lib64/python%s/site-packages' % local_pyshortver],
}

sanity_check_paths = {
    'files': ['bin/gc3utils'],
    'dirs': [('lib/python%s/site-packages' % local_pyshortver, 'lib64/python%s/site-packages' % local_pyshortver)],
}

sanity_check_commands = [('gc3utils', 'info --version')]

moduleclass = 'tools'
```

**Comment by nortex** [comment]
> > Now i have the next error (trying to install the 2.5.0 version to avoid checksum errors):
> 
> You can safely remove the checksums in the edited easyconfig.
> 
> The error you show is a problem untarring something, that's a very strange one, is that a restriction on the filesystem?
> 
> If I was you, I would go back to an edited 2.5.2 version:


Tried it and the error is the same.

Do not know about any restrictions, usually it works. I found that for some users adding a flag --hard-dereference to the tar command solve the problem, how can i add this to the easy config?

**Comment by ocaisa** [comment]
I think you can tweak the extraction command with
```
    ('docutils', '0.15.2', {
        'extract_cmd': ['tar -xzf %s --strip-components 1 --hard-dereference'],
    }),
'': "cp %s %(builddir)s"
```

**Comment by nortex** [comment]
Ok, it proceed further, but now there is a sanity check problem:

It finish installing all extensions, executed with command:

eb --try-software-version=2.5.2 --ignore-checksums GC3Pie-2.5.0.eb

```
== installing extension gc3pie 2.5.0 (28/28)...
== restore after iterating...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /data/sources/build/GC3Pie/2.5.0/dummy-): build failed (first 300 chars): Sanity check failed: extensions sanity check failed for 2 extensions: humanfriendly, gc3pie
failing sanity check for 'humanfriendly' extension: found one or more downloaded dependencies: Downloading https://files.pythonhosted.org/packages/7f/c4/2b0e2d185d9d60772c10350d9853646832609d2f299a8300ab730f1 (took 21 min 34 sec)
== Results of the build can be found in the log file(s) /tmp/eb-qzmIXk/easybuild-GC3Pie-2.5.0-20191029.093820.FIwuK.log
ERROR: Build of /data/apps/Easybuild/ebfiles_repo/GC3Pie/GC3Pie-2.5.0.eb failed (err: "build failed (first 300 chars): Sanity check failed: extensions sanity check failed for 2 extensions: humanfriendly, gc3pie\nfailing sanity check for 'humanfriendly' extension: found one or more downloaded dependencies: Downloading https://files.pythonhosted.org/packages/7f/c4/2b0e2d185d9d60772c10350d9853646832609d2f299a8300ab730f1")
```

**Comment by boegel** [comment]
@nortex You can fix that in one of two ways:

1) (recommended) the sanity check fails because a dependency of `humanfriendly` is being downloaded & installed automatically, without EasyBuild being in control of the version being used (which could lead to the installation no longer working later); to fix this, you should figure out what is being downloaded (by checking the full `Downloading ...` message in the log file), and adding that package in `exts_list` before `humanfriendly`)

2) You can add `download_dep_fail = False` to the easyconfig file to allow auto-downloading of dependencies.

**Comment by branfosj** [comment]
As this bug is in a now archived easyconfig I'll close the issue. If this is a problem with a newer version then please do let us know.
