### ISSUE TITLE
Bazel/0.26.1-GCCcore-8.3.0 requires Python builddep on RHEL/CentOS6

### ISSUE THREAD

**Issue by JackPerdue** [easybuilders/easybuild-easyconfigs#9295]
From: https://github.com/easybuilders/easybuild-easyconfigs/pull/9246

On CentOS6, the build of Bazel/0.26.1-GCCcore-8.3.0 fails with the error below. It seems the CentOS provided python-2.6.6 isn't new enough.  To workaround this problem I had to add a Python builddep.  Either of the below seems to solve the problem.

builddependencies = [('binutils', '2.32'), ('Python', '2.7.16')]
or
builddependencies = [('binutils', '2.32'), ('Python', '3.7.4')]

Traceback (most recent call last):
File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
exec code in run_globals
File "bazel-out/host/bin/src/create_embedded_tools/main.py", line 252, in
File "bazel-out/host/bin/src/create_embedded_tools/main.py", line 181, in Main
File "bazel-out/host/bin/src/create_embedded_tools/main.py", line 132, in CreateModuleSpace
File "bazel-out/host/bin/src/create_embedded_tools/main.py", line 116, in ExtractZip
AttributeError: ZipFile instance has no attribute 'exit'
Target //src:bazel_nojdk failed to build

**Comment by boegel** [comment]
fixed in #9281 9299
